/*
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.ui.tests;

import com.google.inject.Injector;
import de.thm.icampus.joomdd.ejsl.ui.internal.EjslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class EJSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EjslActivator.getInstance().getInjector("de.thm.icampus.joomdd.ejsl.EJSL");
	}

}
