/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.web;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
/* @WebServlet(, )
 */public class EJSLServlet /* implements XtextServlet  */{
  private final /* List<ExecutorService> */Object executorServices /* Skipped initializer because of errors */;
  
  public Object init() {
    throw new Error("Unresolved compilation problems:"
      + "\nProvider cannot be resolved to a type."
      + "\nThe method or field super is undefined"
      + "\nThe method or field Executors is undefined"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type EJSLWebSetup"
      + "\nInvalid number of arguments. The constructor EJSLWebSetup() is not applicable for the arguments (Provider)"
      + "\nExecutorService cannot be resolved to a type."
      + "\ninit cannot be resolved"
      + "\nnewCachedThreadPool cannot be resolved"
      + "\n=> cannot be resolved"
      + "\n+= cannot be resolved");
  }
  
  public Object destroy() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method shutdown() is undefined"
      + "\nThe method or field super is undefined"
      + "\nforEach cannot be resolved"
      + "\nclear cannot be resolved"
      + "\ndestroy cannot be resolved");
  }
}
