/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl;

import de.thm.icampus.joomdd.ejsl.EJSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EJSLStandaloneSetup extends EJSLStandaloneSetupGenerated {
  public static void doSetup() {
    EJSLStandaloneSetup _eJSLStandaloneSetup = new EJSLStandaloneSetup();
    _eJSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
