/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.idea.highlighting;

@SuppressWarnings("all")
public class EJSLColorSettingsPage /* implements EJSLBaseColorSettingsPage  */{
}
