/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getType <em>Type</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#isIsunique <em>Isunique</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getWithattribute <em>Withattribute</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#isId <em>Id</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Isunique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Isunique</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Isunique</em>' attribute.
   * @see #setIsunique(boolean)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute_Isunique()
   * @model
   * @generated
   */
  boolean isIsunique();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#isIsunique <em>Isunique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Isunique</em>' attribute.
   * @see #isIsunique()
   * @generated
   */
  void setIsunique(boolean value);

  /**
   * Returns the value of the '<em><b>Withattribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Withattribute</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Withattribute</em>' reference.
   * @see #setWithattribute(Attribute)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute_Withattribute()
   * @model
   * @generated
   */
  Attribute getWithattribute();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#getWithattribute <em>Withattribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Withattribute</em>' reference.
   * @see #getWithattribute()
   * @generated
   */
  void setWithattribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(boolean)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAttribute_Id()
   * @model
   * @generated
   */
  boolean isId();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Attribute#isId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #isId()
   * @generated
   */
  void setId(boolean value);

} // Attribute
