/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getName <em>Name</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getAuthoremail <em>Authoremail</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getAuthorurl <em>Authorurl</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAuthor()
 * @model
 * @generated
 */
public interface Author extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAuthor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Authoremail</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authoremail</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authoremail</em>' attribute.
   * @see #setAuthoremail(String)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAuthor_Authoremail()
   * @model
   * @generated
   */
  String getAuthoremail();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getAuthoremail <em>Authoremail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authoremail</em>' attribute.
   * @see #getAuthoremail()
   * @generated
   */
  void setAuthoremail(String value);

  /**
   * Returns the value of the '<em><b>Authorurl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authorurl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authorurl</em>' attribute.
   * @see #setAuthorurl(String)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getAuthor_Authorurl()
   * @model
   * @generated
   */
  String getAuthorurl();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Author#getAuthorurl <em>Authorurl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authorurl</em>' attribute.
   * @see #getAuthorurl()
   * @generated
   */
  void setAuthorurl(String value);

} // Author
