/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.CustomPage#getPageType <em>Page Type</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.CustomPage#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getCustomPage()
 * @model
 * @generated
 */
public interface CustomPage extends Page
{
  /**
   * Returns the value of the '<em><b>Page Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.thm.icampus.joomdd.ejsl.eJSL.PageKinds}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Page Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Page Type</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.PageKinds
   * @see #setPageType(PageKinds)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getCustomPage_PageType()
   * @model
   * @generated
   */
  PageKinds getPageType();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.CustomPage#getPageType <em>Page Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Page Type</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.PageKinds
   * @see #getPageType()
   * @generated
   */
  void setPageType(PageKinds value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' reference list.
   * The list contents are of type {@link de.thm.icampus.joomdd.ejsl.eJSL.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' reference list.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getCustomPage_Entities()
   * @model
   * @generated
   */
  EList<Entity> getEntities();

} // CustomPage
