language: java
install: true
before_install:
  - cd de.thm.icampus.joomdd.ejsl.parent
jobs:  
  include:
    - stage: "cleanCache"
      language: minimal
      name: "Clean up the cache"
      script:
        # This cached directory was necessary to be cached for one run
        - rm -f -R $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/de.thm.icampus.joomdd.ejsl.web/build
    - stage: "ca"
      name: "Static Code Analysis"
      script:
        - echo "Do static code analysis here!"
    - stage: "buildArtefacts"
      name: "Build Artefacts"
      script:
        - ./gradlew generateXtextLanguage
    - stage: "test"
      name: "Test Execution"
      jdk: oraclejdk8
      script:
##       - ./gradlew test
        - echo "Do test execution here!"
    - stage: "buildWar"
      name: "Build War File"
      jdk: oraclejdk8
      script:
        - ./gradlew war
        - cd de.thm.icampus.joomdd.ejsl.web/build/libs
        - ls -la
    - stage: "release"
      name: "Create GitHub Release"
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        api_key:
          secure: t6CSX3oonE+ieggFrkIQnMCMxx+a5zameQepFNNvO82nNBJOmoIWqrC7W5robi6fpRqh47xJVQR1r7pM529kNP4gsrYrc98TxAR5i69GfDEoArUuzV0TEzQ78RS3/U7gnyWy5Ow4f1iQufj+KxKpprTpD097s9dMeZv9oeGMS7GbhW8JUEe7U7qunh5bCIP3BZEgNKJQrgAA/EqepzQp99JMaTMWoiCnh/7RZ6YtqYw/QqGum3MZcHv6w53DD2tjw1kOdI9PMvLQqn1Kabrz1JbOjULHYsUpmKGLu8F5nAsXEECtzm/QK3GlWqFcDk0u6+1GBk6QLk2loyC3BHOmolE5+DgXPiyTDqkjlcQnOjHhIJipfQXq4uEaQfeXbmiVmkWAOgJHVvir+CWHvScxsws+7G/LXOU/Vvbr0JM6MA3ANKi2cUP5wEKlu4nhKtWvNthPoVwvOraGsFCzFRhYcmWe5zNgNf2Q0OTWFSEHQMgg5ifaGGh4kKkKP+zZTmlxJBFfR410/9L7U79Xmump3z23gTXlfzZe5E3dbrmeI5hWrVFOhV55XO+JDfhtIK8heyZNNcCHmCsWxMD9hsz8cRJfCzOiWS2tK7URmMjgjuCM4x72iA/ALjEUPZw1tAY+TNU9LHfIX+Z6f7357+CQw4KStfjXFHS2nn6B1a79rp8=
        file: $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/de.thm.icampus.joomdd.ejsl.web/build/libs/*
        on:
          tags: true
          repo: Wolf-Rost/JooMDD
    - stage: "deployToTest"
      name: "Deploy to Test Environment"
      script:
        - echo "Deploy war file in de.thm.icampus.joomdd.ejsl.web/build/libs to test environment."
        
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/
