language: java
install: true
before_install:
  - cd de.thm.icampus.joomdd.ejsl.parent
jobs:  
  include:
    - stage: "cleanCache"
      language: minimal
      name: "Clean up the cache"
      script:
        # This cached directory was necessary to be cached for one run
        - rm -f -R $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/de.thm.icampus.joomdd.ejsl.web/build
    - stage: "ca"
      name: "Static Code Analysis"
      script:
        - echo "Do static code analysis here!"
    - stage: "buildArtefacts"
      name: "Build Artefacts"
      script:
        - ./gradlew generateXtextLanguage
    - stage: "test"
      name: "Test Execution"
      jdk: oraclejdk8
      script:
        - ./gradlew test
    - stage: "buildWar"
      name: "Build War File"
      jdk: oraclejdk8
      script:
        - ./gradlew war
        - cd de.thm.icampus.joomdd.ejsl.web/build/libs
        - ls -la
    - stage: "release"
      name: "Create GitHub Release"
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file_glob: true
        skip_cleanup: true
        api_key:
          secure: $api_token
        file: $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/de.thm.icampus.joomdd.ejsl.web/build/libs/*
        on:
          tags: true
          repo: Wolf-Rost/JooMDD
    - stage: "deployToTest"
      name: "Deploy to Test Environment"
      script:
        - echo "Deploy war file in de.thm.icampus.joomdd.ejsl.web/build/libs to test environment."
        
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $TRAVIS_BUILD_DIR/de.thm.icampus.joomdd.ejsl.parent/
