/*
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import de.thm.icampus.joomdd.ejsl.idea.lang.EJSLLanguage;

public class EJSLExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return EJSLLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
