<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CMSDSL" nsURI="http://www.icampus.thm.de/CMSDSL" nsPrefix="CMSDSL">
  <eClassifiers xsi:type="ecore:EClass" name="CMSModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" lowerBound="1" eType="#//CMSPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMSCore" eSuperTypes="#//CMSPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corefeatures" upperBound="-1"
        eType="#//CoreFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMSPart" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="CMSFeature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//Configuration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreFeature" abstract="true" eSuperTypes="#//CMSFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//CMSFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticPage" eSuperTypes="#//Page"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="localparameters" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalparameters" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametergroups" upperBound="-1"
        eType="#//Parametergroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionKind" eType="#//SectionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entitypackage" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityPackages" upperBound="-1"
        eType="#//Entitypackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatypes" upperBound="-1"
        eType="#//Datatype" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMSExtension" eSuperTypes="#//CMSPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" eType="#//Manifestation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//Language" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPage" eSuperTypes="#//DynamicPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsPage" eSuperTypes="#//DynamicPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesslevels" upperBound="-1"
        eType="#//AccessLevel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributepackages" upperBound="-1"
        eType="#//AttributePackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityReference" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageReference" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dbtype" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="htmltype" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleDataType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SimpleDatatypeKinds"
        defaultValueLiteral="string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeReference" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleDatatypeKinds">
    <eLiterals name="bool"/>
    <eLiterals name="string"/>
    <eLiterals name="int"/>
    <eLiterals name="float"/>
    <eLiterals name="array"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametergroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalLink" eSuperTypes="#//Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalLink" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextLink" eSuperTypes="#//InternalLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkparameters" upperBound="-1"
        eType="#//LinkParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributereference" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionPackage" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//CMSExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//CMSExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" upperBound="-1"
        eType="#//Position" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cssblocks" upperBound="-1"
        eType="#//CSSBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SectionKind">
    <eLiterals name="backend"/>
    <eLiterals name="frontend"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//MethodParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" eType="#//Package"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manifestation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Author" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author"/>
  <eClassifiers xsi:type="ecore:EClass" name="Language" eSuperTypes="#//KVPairObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValuePair"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSSBlock" eSuperTypes="#//KVPairObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="PositionParameter" eSuperTypes="#//KVPairObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyvaluepairs" upperBound="-1"
        eType="#//KeyValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionparameters" upperBound="-1"
        eType="#//PositionParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rights" upperBound="-1"
        eType="#//Right" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Right"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributePackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Enumliteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumliteral"/>
</ecore:EPackage>
