package de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator;

import de.thm.icampus.joomdd.ejsl.eJSL.Entity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedEntity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedExtension.ExtendedComponent;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDetailPageField;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDynamicPage;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaUtil.Slug;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class DetailsPageTemplateBackendHelper {
  private ExtendedDynamicPage dpage;
  
  private ExtendedComponent com;
  
  private String sec;
  
  public DetailsPageTemplateBackendHelper(final ExtendedDynamicPage dp, final ExtendedComponent cp, final String section) {
    this.dpage = dp;
    this.com = cp;
    this.sec = section;
  }
  
  public CharSequence generateAdminModelprepareTableFunction() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Prepare and sanitise the table prior to saving.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("protected function prepareTable($table)");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("jimport(\'joomla.filter.output\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (empty($table->id)) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Set ordering to the last item if not set");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (@$table->ordering === \'\') {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("$db = JFactory::getDbo();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("$db->setQuery(\'SELECT MAX(ordering) FROM #__");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t\t\t");
    _builder.append("_");
    EList<Entity> _entities = this.dpage.getEntities();
    Entity _get = _entities.get(0);
    String _name_1 = _get.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "\t\t\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("$max = $db->loadResult();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("$table->ordering = $max+1;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminModelTableFunction() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Returns a reference to the a Table object, always creating it.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @param\ttype\tThe table type to instantiate");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @param\tstring\tA prefix for the table class name. Optional.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @param\tarray\tConfiguration array for model. Optional.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @return\tJTable\tA database object");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public function getTable($type = \'");
    EList<Entity> _entities = this.dpage.getEntities();
    Entity _get = _entities.get(0);
    String _name = _get.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("\', $prefix = \'");
    String _name_1 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append("Table\', $config = array())");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return JTable::getInstance($type, $prefix, $config);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminViewAddToolbar() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Add the page title and toolbar.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected function addToolbar() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("JFactory::getApplication()->input->set(\'hidemainmenu\', true);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$isNew = ($this->item->id == 0);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (isset($this->item->checked_out)) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$checkedOut = !($this->item->checked_out == 0 || $this->item->checked_out == $user->get(\'id\'));");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$checkedOut = false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$canDo = ");
    String _name = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "        ");
    _builder.append("Helper::getActions();");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("JToolBarHelper::title(JText::_(\'COM_");
    String _name_1 = this.com.getName();
    String _upperCase = _name_1.toUpperCase();
    _builder.append(_upperCase, "        ");
    _builder.append("_TITLE_");
    String _name_2 = this.dpage.getName();
    String _upperCase_1 = _name_2.toUpperCase();
    _builder.append(_upperCase_1, "        ");
    _builder.append("\'), \'");
    String _name_3 = this.dpage.getName();
    String _lowerCase = _name_3.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append(".png\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// If not checked out, can save the item.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!$checkedOut && ($canDo->get(\'core.edit\') || ($canDo->get(\'core.create\')))) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JToolBarHelper::apply(\'");
    String _name_4 = this.dpage.getName();
    String _lowerCase_1 = _name_4.toLowerCase();
    _builder.append(_lowerCase_1, "            ");
    _builder.append(".apply\', \'JTOOLBAR_APPLY\');");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("JToolBarHelper::save(\'");
    String _name_5 = this.dpage.getName();
    String _lowerCase_2 = _name_5.toLowerCase();
    _builder.append(_lowerCase_2, "            ");
    _builder.append(".save\', \'JTOOLBAR_SAVE\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!$checkedOut && ($canDo->get(\'core.create\'))) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JToolBarHelper::custom(\'");
    String _name_6 = this.dpage.getName();
    String _lowerCase_3 = _name_6.toLowerCase();
    _builder.append(_lowerCase_3, "            ");
    _builder.append(".save2new\', \'save-new.png\', \'save-new_f2.png\', \'JTOOLBAR_SAVE_AND_NEW\', false);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// If an existing item, can save to a copy.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!$isNew && $canDo->get(\'core.create\')) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JToolBarHelper::custom(\'");
    String _name_7 = this.dpage.getName();
    String _lowerCase_4 = _name_7.toLowerCase();
    _builder.append(_lowerCase_4, "            ");
    _builder.append(".save2copy\', \'save-copy.png\', \'save-copy_f2.png\', \'JTOOLBAR_SAVE_AS_COPY\', false);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (empty($this->item->id)) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JToolBarHelper::cancel(\'");
    String _name_8 = this.dpage.getName();
    String _lowerCase_5 = _name_8.toLowerCase();
    _builder.append(_lowerCase_5, "            ");
    _builder.append(".cancel\', \'JTOOLBAR_CANCEL\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JToolBarHelper::cancel(\'");
    String _name_9 = this.dpage.getName();
    String _lowerCase_6 = _name_9.toLowerCase();
    _builder.append(_lowerCase_6, "            ");
    _builder.append(".cancel\', \'JTOOLBAR_CLOSE\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminViewDisplay() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("* Display the view");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public function display($tpl = null) {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$this->setLayout(\'Edit\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$this->state = $this->get(\'State\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$this->item = $this->get(\'Item\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$this->form = $this->get(\'Form\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (count($errors = $this->get(\'Errors\'))) {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("throw new Exception(implode(\"\\n\", $errors));");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$this->addToolbar();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("parent::display($tpl);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminViewLayoutFormular() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<form action=\"<?php echo JRoute::_(\'index.php?option=com_");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append("&layout=edit&id=\' . (int) $this->item->id); ?>\" method=\"post\" enctype=\"multipart/form-data\" name=\"adminForm\" id=\"");
    String _name_1 = this.dpage.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append("-form\" class=\"form-validate\">");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"form-horizontal\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<?php echo JHtml::_(\'bootstrap.startTabSet\', \'myTab\', array(\'active\' => \'general\')); ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<?php echo JHtml::_(\'bootstrap.addTab\', \'myTab\', \'general\', JText::_(\'COM_");
    String _name_2 = this.com.getName();
    String _upperCase = _name_2.toUpperCase();
    _builder.append(_upperCase, "        ");
    _builder.append("_TITLE_");
    String _name_3 = this.dpage.getName();
    String _upperCase_1 = _name_3.toUpperCase();
    _builder.append(_upperCase_1, "        ");
    _builder.append("\', true)); ?>");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("<div class=\"row-fluid\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<div class=\"span10 form-horizontal\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<fieldset class=\"adminform\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<input type=\"hidden\" name=\"jform[id]\" value=\"<?php echo $this->item->id; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[ordering]\" value=\"<?php echo $this->item->ordering; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[state]\" value=\"<?php echo $this->item->state; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[published]\" value=\"<?php if($this->item->id != 0) echo $this->item->state; else echo 1;?>\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[checked_out]\" value=\"<?php if(isset($this->item->checked_out)){");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("echo $this->item->checked_out;}else{ echo JFactory::getUser()->id;} ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[checked_out_time]\" value=\"<?php if(isset($this->item->checked_out_time)){");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("echo $this->item->checked_out_time;}else{ echo date(\"Y-m-d H:i:s\") ;} ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<?php if(empty($this->item->created_by)){ ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[created_by]\" value=\"<?php echo JFactory::getUser()->id; ?>\" />");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<?php } ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("else{ ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[created_by]\" value=\"<?php echo $this->item->created_by; ?>\" />");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<?php } ?>");
    _builder.newLine();
    _builder.append("\t\t\t");
    EList<ExtendedDetailPageField> _extendedEditedFieldsList = this.dpage.getExtendedEditedFieldsList();
    EList<ExtendedEntity> _extendedEntityList = this.dpage.getExtendedEntityList();
    ExtendedEntity _get = _extendedEntityList.get(0);
    CharSequence _generateEntytiesInputAttribute = Slug.generateEntytiesInputAttribute(_extendedEditedFieldsList, _get);
    _builder.append(_generateEntytiesInputAttribute, "\t\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t   ");
    _builder.append("</fieldset>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<?php echo JHtml::_(\'bootstrap.endTab\'); ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<?php if (JFactory::getUser()->authorise(\'core.admin\',\'");
    String _name_4 = this.com.getName();
    String _lowerCase_2 = _name_4.toLowerCase();
    _builder.append(_lowerCase_2, "\t    ");
    _builder.append("\')) : ?>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("<?php echo JHtml::_(\'bootstrap.addTab\', \'myTab\', \'permissions\', JText::_(\'JGLOBAL_ACTION_PERMISSIONS_LABEL\', true)); ?>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<?php echo $this->form->getInput(\'rules\'); ?>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<?php echo JHtml::_(\'bootstrap.endTab\'); ?>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<?php echo JHtml::_(\'bootstrap.endTabSet\'); ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<input type=\"hidden\" name=\"task\" value=\"\" />");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<?php echo JHtml::_(\'form.token\'); ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</form>");
    _builder.newLine();
    return _builder;
  }
}
