package de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator;

import de.thm.icampus.joomdd.ejsl.eJSL.Attribute;
import de.thm.icampus.joomdd.ejsl.eJSL.Entity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedAttribute;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedEntity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedExtension.ExtendedComponent;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDetailPageField;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDynamicPage;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaUtil.Slug;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class DetailsPageTemplateFrontEndHelper {
  private ExtendedDynamicPage dpage;
  
  private ExtendedComponent com;
  
  private String sec;
  
  public DetailsPageTemplateFrontEndHelper(final ExtendedDynamicPage dp, final ExtendedComponent cp, final String section) {
    this.dpage = dp;
    this.com = cp;
    this.sec = section;
  }
  
  public CharSequence generateSiteControllerEdit(final Boolean isedit) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Method to check out an item for editing and redirect to the edit form.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public function edit() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Get the previous edit id (if any) and the current edit id.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$previousId = (int) $app->getUserState(\'com_");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append(".edit.");
    String _name_1 = this.dpage.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "        ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("$editId = JFactory::getApplication()->input->getInt(\'id\', null, \'array\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Set the user id for the user to edit in the session.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app->setUserState(\'com_");
    String _name_2 = this.com.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "        ");
    _builder.append(".edit.");
    String _name_3 = this.dpage.getName();
    String _lowerCase_3 = _name_3.toLowerCase();
    _builder.append(_lowerCase_3, "        ");
    _builder.append(".id\', $editId);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Get the model.");
    _builder.newLine();
    {
      if ((isedit).booleanValue()) {
        _builder.append("        ");
        _builder.append("$model = $this->getModel(\'");
        String _name_4 = this.dpage.getName();
        String _firstUpper = StringExtensions.toFirstUpper(_name_4);
        _builder.append(_firstUpper, "        ");
        _builder.append("Edit\', \'");
        String _name_5 = this.com.getName();
        String _firstUpper_1 = StringExtensions.toFirstUpper(_name_5);
        _builder.append(_firstUpper_1, "        ");
        _builder.append("Model\');");
        _builder.newLineIfNotEmpty();
      } else {
        _builder.append("        ");
        _builder.append("$model = $this->getModel(\'");
        String _name_6 = this.dpage.getName();
        String _firstUpper_2 = StringExtensions.toFirstUpper(_name_6);
        _builder.append(_firstUpper_2, "        ");
        _builder.append("\', \'");
        String _name_7 = this.com.getName();
        String _firstUpper_3 = StringExtensions.toFirstUpper(_name_7);
        _builder.append(_firstUpper_3, "        ");
        _builder.append("Model\');");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check out the item");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($editId) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$model->checkout($editId);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check in the previous user.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($previousId && $previousId !== $editId) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$model->checkin($previousId);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Redirect to the edit screen.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->setRedirect(JRoute::_(\'index.php?option=com_");
    String _name_8 = this.com.getName();
    String _lowerCase_4 = _name_8.toLowerCase();
    _builder.append(_lowerCase_4, "        ");
    _builder.append("&view=");
    String _name_9 = this.dpage.getName();
    String _lowerCase_5 = _name_9.toLowerCase();
    _builder.append(_lowerCase_5, "        ");
    String _xifexpression = null;
    if ((isedit).booleanValue()) {
      _xifexpression = "edit";
    }
    _builder.append(_xifexpression, "        ");
    _builder.append("&layout=edit\', false));");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteControllerSave() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Method to save the data.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @return\tvoid");
    _builder.newLine();
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public function save() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check for request forgeries.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("JSession::checkToken() or jexit(JText::_(\'JINVALID_TOKEN\'));");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Initialise variables.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$model = $this->getModel(\'");
    String _name = this.dpage.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "\t        ");
    _builder.append("Edit\', \'");
    String _name_1 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "\t        ");
    _builder.append("Model\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Get the user data.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$data = JFactory::getApplication()->input->get(\'jform\', array(), \'array\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Validate the posted data.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$form = $model->getForm();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!$form) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JError::raiseError(500, $model->getError());");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Validate the posted data.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$data = $model->validate($form, $data);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($data === false) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Get the validation messages.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$errors = $model->getErrors();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Push up to three validation messages out to the user.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if ($errors[$i] instanceof Exception) {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("$app->enqueueMessage($errors[$i]->getMessage(), \'warning\');");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("$app->enqueueMessage($errors[$i], \'warning\');");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$input = $app->input;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$jform = $input->get(\'jform\', array(), \'ARRAY\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Save the data in the session.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$app->setUserState(\'com_");
    String _name_2 = this.com.getName();
    String _lowerCase = _name_2.toLowerCase();
    _builder.append(_lowerCase, "            ");
    _builder.append(".edit.");
    String _name_3 = this.dpage.getName();
    String _lowerCase_1 = _name_3.toLowerCase();
    _builder.append(_lowerCase_1, "            ");
    _builder.append(".data\', $jform, array());");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Redirect back to the edit screen.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$id = (int) $app->getUserState(\'com_");
    String _name_4 = this.com.getName();
    String _lowerCase_2 = _name_4.toLowerCase();
    _builder.append(_lowerCase_2, "            ");
    _builder.append(".edit.");
    String _name_5 = this.dpage.getName();
    String _lowerCase_3 = _name_5.toLowerCase();
    _builder.append(_lowerCase_3, "            ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("$this->setRedirect(JRoute::_(\'index.php?option=com_");
    String _name_6 = this.com.getName();
    String _lowerCase_4 = _name_6.toLowerCase();
    _builder.append(_lowerCase_4, "            ");
    _builder.append("&view=");
    String _name_7 = this.dpage.getName();
    String _lowerCase_5 = _name_7.toLowerCase();
    _builder.append(_lowerCase_5, "            ");
    _builder.append("edit&layout=edit&id=\' . $id, false));");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Attempt to save the data.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$return = $model->save($data);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($return === false) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Save the data in the session.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$app->setUserState(\'com_");
    String _name_8 = this.com.getName();
    String _lowerCase_6 = _name_8.toLowerCase();
    _builder.append(_lowerCase_6, "            ");
    _builder.append(".edit.");
    String _name_9 = this.dpage.getName();
    String _lowerCase_7 = _name_9.toLowerCase();
    _builder.append(_lowerCase_7, "            ");
    _builder.append(".data\', $data);");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Redirect back to the edit screen.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$id = (int) $app->getUserState(\'com_");
    String _name_10 = this.com.getName();
    String _lowerCase_8 = _name_10.toLowerCase();
    _builder.append(_lowerCase_8, "            ");
    _builder.append(".edit.");
    String _name_11 = this.dpage.getName();
    String _lowerCase_9 = _name_11.toLowerCase();
    _builder.append(_lowerCase_9, "            ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("$this->setMessage(JText::sprintf(\'Save failed\', $model->getError()), \'warning\');");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$this->setRedirect(JRoute::_(\'index.php?option=com_");
    String _name_12 = this.com.getName();
    String _lowerCase_10 = _name_12.toLowerCase();
    _builder.append(_lowerCase_10, "            ");
    _builder.append("&view=");
    String _name_13 = this.dpage.getName();
    String _lowerCase_11 = _name_13.toLowerCase();
    _builder.append(_lowerCase_11, "            ");
    _builder.append("edit&layout=edit&id=\' . $id, false));");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check in the profile.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($return) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$model->checkin($return);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Clear the profile id from the session.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app->setUserState(\'com_");
    String _name_14 = this.com.getName();
    String _lowerCase_12 = _name_14.toLowerCase();
    _builder.append(_lowerCase_12, "        ");
    _builder.append(".edit.");
    String _name_15 = this.dpage.getName();
    String _lowerCase_13 = _name_15.toLowerCase();
    _builder.append(_lowerCase_13, "        ");
    _builder.append(".id\', null);");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Redirect to the list screen.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->setMessage(JText::_(\'COM_");
    String _name_16 = this.com.getName();
    String _upperCase = _name_16.toUpperCase();
    _builder.append(_upperCase, "        ");
    _builder.append("_ITEM_SAVED_SUCCESSFULLY\'));");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("$menu = JFactory::getApplication()->getMenu();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$item = $menu->getActive();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$url = (empty($item->link) ? \'index.php?\' : $item->link);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->setRedirect(JRoute::_($url, false));");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Flush the data from the session.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app->setUserState(\'com_");
    String _name_17 = this.com.getName();
    String _lowerCase_14 = _name_17.toLowerCase();
    _builder.append(_lowerCase_14, "        ");
    _builder.append(".edit.");
    String _name_18 = this.dpage.getName();
    String _lowerCase_15 = _name_18.toLowerCase();
    _builder.append(_lowerCase_15, "        ");
    _builder.append(".data\', null);");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteControllerCancel() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* To cancel the Edit of a Item");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("function cancel() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("// Get the current edit id.");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$editId = (int) $app->getUserState(\'com_");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t        ");
    _builder.append(".edit.");
    String _name_1 = this.dpage.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "\t        ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("// Get the model.");
    _builder.newLine();
    _builder.append("\t       ");
    _builder.append("$model = $this->getModel(\'");
    String _name_2 = this.dpage.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper, "\t       ");
    _builder.append("Edit\', \'");
    String _name_3 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_1, "\t       ");
    _builder.append("Model\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("// Check in the item");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if ($editId) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$model->checkin($editId);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$menu = JFactory::getApplication()->getMenu();");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$item = $menu->getActive();");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$url = (empty($item->link) ? \'index.php?\' : $item->link);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$this->setRedirect(JRoute::_($url, false));");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteControllerRemove() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*Delete a Item");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public function remove() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("// Initialise variables.");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("//Checking if the user can remove object");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if ($user->authorise($user->authorise(\'core.delete\', \'com_");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t        ");
    _builder.append("\'))) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("$model = $this->getModel(\'");
    String _name_1 = this.dpage.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper, "\t            ");
    _builder.append("\', \'");
    String _name_2 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_1, "\t            ");
    _builder.append("Model\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Get the user data.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$id = $app->input->getInt(\'id\', 0);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Attempt to delete the data.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$return = $model->delete($id);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if ($return === false) {");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$this->setMessage(JText::sprintf(\'Delete failed\', $model->getError()), \'warning\');");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("// Check in the profile.");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("if ($return) {");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("$model->checkin($return);");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("// Clear the profile id from the session.");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$app->setUserState(\'com_");
    String _name_3 = this.com.getName();
    String _lowerCase_1 = _name_3.toLowerCase();
    _builder.append(_lowerCase_1, "\t                ");
    _builder.append(".edit.");
    String _name_4 = this.dpage.getName();
    String _lowerCase_2 = _name_4.toLowerCase();
    _builder.append(_lowerCase_2, "\t                ");
    _builder.append(".id\', null);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("// Flush the data from the session.");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$app->setUserState(\'com_");
    String _name_5 = this.com.getName();
    String _lowerCase_3 = _name_5.toLowerCase();
    _builder.append(_lowerCase_3, "\t                ");
    _builder.append(".edit.");
    String _name_6 = this.dpage.getName();
    String _lowerCase_4 = _name_6.toLowerCase();
    _builder.append(_lowerCase_4, "\t                ");
    _builder.append(".data\', null);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$this->setMessage(JText::_(\'COM_");
    String _name_7 = this.com.getName();
    String _upperCase = _name_7.toUpperCase();
    _builder.append(_upperCase, "\t                ");
    _builder.append("_ITEM_DELETED_SUCCESSFULLY\'));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Redirect to the list screen.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$menu = & JSite::getMenu();");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$item = $menu->getActive();");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$this->setRedirect(JRoute::_($item->link, false));");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("throw new Exception(500);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelPopulatestate() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Method to auto-populate the model state.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* Note. Calling getState in this method will result in recursion.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected function populateState() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app = JFactory::getApplication(\'com_");
    String _name = this.com.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Load state from the request userState on edit or from the passed variable on default");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (JFactory::getApplication()->input->get(\'layout\') == \'edit\') {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$id = JFactory::getApplication()->getUserState(\'com_");
    String _name_1 = this.com.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "            ");
    _builder.append(".edit.");
    String _name_2 = this.dpage.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "            ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$id = JFactory::getApplication()->input->get(\'id\');");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JFactory::getApplication()->setUserState(\'com_");
    String _name_3 = this.com.getName();
    String _lowerCase_3 = _name_3.toLowerCase();
    _builder.append(_lowerCase_3, "            ");
    _builder.append(".edit.");
    String _name_4 = this.dpage.getName();
    String _lowerCase_4 = _name_4.toLowerCase();
    _builder.append(_lowerCase_4, "            ");
    _builder.append(".id\', $id);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->setState(\'");
    String _name_5 = this.dpage.getName();
    String _lowerCase_5 = _name_5.toLowerCase();
    _builder.append(_lowerCase_5, "        ");
    _builder.append(".id\', $id);");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Load the parameters.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$params = $app->getParams();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$params_array = $params->toArray();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (isset($params_array[\'item_id\'])) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$this->setState(\'");
    String _name_6 = this.dpage.getName();
    String _lowerCase_6 = _name_6.toLowerCase();
    _builder.append(_lowerCase_6, "            ");
    _builder.append(".id\', $params_array[\'item_id\']);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->setState(\'params\', $params);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelgetData(final Boolean isEdit) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Method to get an ojbect.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @param\tinteger\tThe id of the object to get.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @return\tmixed\tObject on success, false on failure.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public function &getData($id = null) {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if ($this->_item === null) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$this->_item = false;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if (empty($id)) {");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$id = $this->getState(\'");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t                ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Get a level row instance.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("// Attempt to load the row.");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if ($table->load($id)) {");
    _builder.newLine();
    {
      if ((isEdit).booleanValue()) {
        _builder.append("$user = JFactory::getUser();");
        _builder.newLine();
        _builder.append("$id = $table->id;");
        _builder.newLine();
        _builder.append("if($id){");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("$canEdit = $user->authorise(\'core.edit\', \'com_");
        String _name_1 = this.com.getName();
        String _lowerCase_1 = _name_1.toLowerCase();
        _builder.append(_lowerCase_1, "\t");
        _builder.append(".");
        String _name_2 = this.dpage.getName();
        String _lowerCase_2 = _name_2.toLowerCase();
        _builder.append(_lowerCase_2, "\t");
        _builder.append(".\'.$id) ");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("|| $user->authorise(\'core.create\', \'com_");
        String _name_3 = this.com.getName();
        String _lowerCase_3 = _name_3.toLowerCase();
        _builder.append(_lowerCase_3, "\t");
        _builder.append(".");
        String _name_4 = this.dpage.getName();
        String _lowerCase_4 = _name_4.toLowerCase();
        _builder.append(_lowerCase_4, "\t");
        _builder.append(".\'.$id);");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("else{");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("$canEdit = $user->authorise(\'core.edit\', \'com_");
        String _name_5 = this.com.getName();
        String _lowerCase_5 = _name_5.toLowerCase();
        _builder.append(_lowerCase_5, "\t");
        _builder.append("\') || $user->authorise(\'core.create\', \'com_");
        String _name_6 = this.com.getName();
        String _lowerCase_6 = _name_6.toLowerCase();
        _builder.append(_lowerCase_6, "\t");
        _builder.append("\');");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("if (!$canEdit && $user->authorise(\'core.edit.own\', \'com_");
        String _name_7 = this.com.getName();
        String _lowerCase_7 = _name_7.toLowerCase();
        _builder.append(_lowerCase_7, "");
        _builder.append(".");
        String _name_8 = this.dpage.getName();
        String _lowerCase_8 = _name_8.toLowerCase();
        _builder.append(_lowerCase_8, "");
        _builder.append(".\'.$id)) {");
        _builder.newLineIfNotEmpty();
        _builder.append("$canEdit = $user->id == $table->created_by;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("if (!$canEdit) {");
        _builder.newLine();
        _builder.append("JError::raiseError(\'500\', JText::_(\'JERROR_ALERTNOAUTHOR\'));");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("\t                ");
    _builder.append("// Check published state.");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("if ($published = $this->getState(\'filter.published\')) {");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("if ($table->state != $published) {");
    _builder.newLine();
    _builder.append("\t                        ");
    _builder.append("return $this->_item;");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("// Convert the JTable to a clean JObject.");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$properties = $table->getProperties(1);");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$this->_item = JArrayHelper::toObject($properties, \'JObject\');");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("} elseif ($error = $table->getError()) {");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("$this->setError($error);");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if ( isset($this->_item->created_by) ) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("$this->_item->created_by_name = JFactory::getUser($this->_item->created_by)->name;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if ( isset($this->_item->user) ) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("$this->_item->user_name = JFactory::getUser($this->_item->user)->name;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("return $this->_item;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelgetTable() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public function getTable($type = \'");
    EList<Entity> _entities = this.dpage.getEntities();
    Entity _get = _entities.get(0);
    String _name = _get.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("\', $prefix = \'");
    String _name_1 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append("Table\', $config = array()) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("$this->addTablePath(JPATH_COMPONENT_ADMINISTRATOR . \'/tables\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return JTable::getInstance($type, $prefix, $config);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelCheckin() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Method to check in an item.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @param\tinteger\t\tThe id of the row to check out.");
    _builder.newLine();
    _builder.append("* @return\tboolean\t\tTrue on success, false on failure.");
    _builder.newLine();
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("public function checkin($id = null) {");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("// Get the id.");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$id = (!empty($id)) ? $id : (int) $this->getState(\'");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "       ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($id) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("           ");
    _builder.append("// Initialise the table");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("           ");
    _builder.append("// Attempt to check the row in.");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("if (method_exists($table, \'checkin\')) {");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("if (!$table->checkin($id)) {");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("$this->setError($table->getError());");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelCheckout() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Method to check out an item for editing.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @param\tinteger\t\tThe id of the row to check out.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @return\tboolean\t\tTrue on success, false on failure.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public function checkout($id = null) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Get the user id.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$id = (!empty($id)) ? $id : (int) $this->getState(\'");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($id) {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Initialise the table");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Get the current user object.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Attempt to check the row out.");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (method_exists($table, \'checkout\')) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if (!$table->checkout($user->get(\'id\'), $id)) {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("$this->setError($table->getError());");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelSave() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Method to save the form data.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @param\tarray\t\tThe form data.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @return\tmixed\t\tThe user id on success, false on failure.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public function save($data)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("$id = (!empty($data[\'id\'])) ? $data[\'id\'] : (int)$this->getState(\'");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t\t");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("$state = (!empty($data[\'state\'])) ? 1 : 0;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if($id) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("//Check the user can edit this item");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$authorised = $user->authorise(\'core.edit\', \'");
    String _name_1 = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name_1);
    String _lowerCase_1 = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase_1, "            ");
    _builder.append(".");
    String _name_2 = this.dpage.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "            ");
    _builder.append(".\'.$id) ");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("|| $authorised = $user->authorise(\'core.edit.own\', \'");
    String _name_3 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_3);
    String _lowerCase_3 = _nameExtensionBind_1.toLowerCase();
    _builder.append(_lowerCase_3, "            ");
    _builder.append(".");
    String _name_4 = this.dpage.getName();
    String _lowerCase_4 = _name_4.toLowerCase();
    _builder.append(_lowerCase_4, "            ");
    _builder.append(".\'.$id);");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("if($user->authorise(\'core.edit.state\', \'");
    String _name_5 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_5);
    String _lowerCase_5 = _nameExtensionBind_2.toLowerCase();
    _builder.append(_lowerCase_5, "            ");
    _builder.append(".");
    String _name_6 = this.dpage.getName();
    String _lowerCase_6 = _name_6.toLowerCase();
    _builder.append(_lowerCase_6, "            ");
    _builder.append(".\'.$id) !== true && $state == 1){ //The user cannot edit the state of the item.");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("$data[\'state\'] = 0;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("//Check the user can create new items in this section");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("$authorised = $user->authorise(\'core.create\', \'");
    String _name_7 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_7);
    String _lowerCase_7 = _nameExtensionBind_3.toLowerCase();
    _builder.append(_lowerCase_7, "            ");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("if($user->authorise(\'core.edit.state\', \'");
    String _name_8 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_8);
    String _lowerCase_8 = _nameExtensionBind_4.toLowerCase();
    _builder.append(_lowerCase_8, "            ");
    _builder.append(".");
    String _name_9 = this.dpage.getName();
    String _lowerCase_9 = _name_9.toLowerCase();
    _builder.append(_lowerCase_9, "            ");
    _builder.append(".\'.$id) !== true && $state == 1){ //The user cannot edit the state of the item.");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("$data[\'state\'] = 0;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($authorised !== true) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("JError::raiseError(403, JText::_(\'JERROR_ALERTNOAUTHOR\'));");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($table->save($data) === true) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return $table->id;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelDelete() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* to Delete Data of a Item");
    _builder.newLine();
    _builder.append("*@param Int $data   content the Id");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t ");
    _builder.append("function delete($data)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$id = (!empty($data)) ? $data : (int)$this->getState(\'");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append(".id\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("if(JFactory::getUser()->authorise(\'core.delete\', \'");
    String _name_1 = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name_1);
    String _lowerCase_1 = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase_1, "        ");
    _builder.append(".");
    String _name_2 = this.dpage.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "        ");
    _builder.append(".\'.$id) !== true){");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("JError::raiseError(403, JText::_(\'JERROR_ALERTNOAUTHOR\'));");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if ($table->delete($data) === true) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return $id;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelgetCategory() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* to search the Category name");
    _builder.newLine();
    _builder.append("*@param Int $id   content the Id");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public function getCategoryName($id) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$db = JFactory::getDbo();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$query = $db->getQuery(true);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$query");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("->select(\'title\')");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("->from(\'#__categories\')");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("->where(\'id = \' . $id);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$db->setQuery($query);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return $db->loadObject();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteModelpublish() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* check, if the item published");
    _builder.newLine();
    _builder.append("*@param Int $id   content the Id");
    _builder.newLine();
    _builder.append("*@param Int $state");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("*/ ");
    _builder.newLine();
    _builder.append("public function publish($id, $state) {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$table = $this->getTable();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$table->load($id);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$table->state = $state;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("return $table->store();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteViewDisplay(final Boolean isedit) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Display the view");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public function display($tpl = null) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->state = $this->get(\'State\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->item = $this->get(\'Item\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->params = $app->getParams(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _lowerCase = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    {
      if ((isedit).booleanValue()) {
        _builder.append("\t\t");
        _builder.append("$this->setLayout(\'Edit\');");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("$this->form\t\t= $this->get(\'Form\');");
        _builder.newLine();
      } else {
        _builder.append("\t\t");
        _builder.append("if (!empty($this->item)) {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("$this->form\t\t= $this->get(\'Form\');");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (count($errors = $this->get(\'Errors\'))) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new Exception(implode(\"\\n\", $errors));");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    {
      if ((!(isedit).booleanValue())) {
        _builder.append("\t\t");
        _builder.append("if ($this->_layout == \'edit\') {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("$authorised = $user->authorise(\'core.create\', \'");
        String _name_1 = this.com.getName();
        String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_1);
        String _lowerCase_1 = _nameExtensionBind_1.toLowerCase();
        _builder.append(_lowerCase_1, "\t\t");
        _builder.append("\');");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("if ($authorised !== true) {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("throw new Exception(JText::_(\'JERROR_ALERTNOAUTHOR\'));");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("        ");
    _builder.append("$this->_prepareDocument();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("parent::display($tpl);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteViewprepareDocument() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Prepares the document");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("protected function _prepareDocument() {");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$menus = $app->getMenu();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$title = null;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("// Because the application sets a default page title,");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("// we need to get it from the menu item itself");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$menu = $menus->getActive();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($menu) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->params->def(\'page_heading\', $this->params->get(\'page_title\', $menu->title));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->params->def(\'page_heading\', JText::_(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _upperCase = _nameExtensionBind.toUpperCase();
    _builder.append(_upperCase, "           ");
    _builder.append("_DEFAULT_PAGE_TITLE\'));");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$title = $this->params->get(\'page_title\', \'\');");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if (empty($title)) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = $app->getCfg(\'sitename\');");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} elseif ($app->getCfg(\'sitename_pagetitles\', 0) == 1) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = JText::sprintf(\'JPAGETITLE\', $app->getCfg(\'sitename\'), $title);");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} elseif ($app->getCfg(\'sitename_pagetitles\', 0) == 2) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = JText::sprintf(\'JPAGETITLE\', $title, $app->getCfg(\'sitename\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$this->document->setTitle($title);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'menu-meta_description\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setDescription($this->params->get(\'menu-meta_description\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'menu-meta_keywords\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setMetadata(\'keywords\', $this->params->get(\'menu-meta_keywords\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'robots\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setMetadata(\'robots\', $this->params->get(\'robots\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteViewLayoutEditForm() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<form id=\"form-");
    String _name = this.dpage.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append("\" action=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_1 = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name_1);
    String _lowerCase_1 = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append("&task=");
    String _name_2 = this.dpage.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append("edit.save\'); ?>\" method=\"post\" class=\"form-validate form-horizontal\" enctype=\"multipart/form-data\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[id]\" value=\"<?php echo $this->item->id; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[ordering]\" value=\"<?php echo $this->item->ordering; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[state]\" value=\"<?php echo $this->item->state; ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[checked_out]\" value=\"<?php if(isset($this->item->checked_out)){");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("echo $this->item->checked_out;}else{ echo JFactory::getUser()->id;} ?>\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"hidden\" name=\"jform[checked_out_time]\" value=\"<?php if(isset($this->item->checked_out_time)){");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("echo $this->item->checked_out_time;}else{ echo date(\"Y-m-d H:i:s\") ;} ?>\" />");
    _builder.newLine();
    _builder.append("<?php if(empty($this->item->created_by)): ?>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<input type=\"hidden\" name=\"jform[created_by]\" value=\"<?php echo JFactory::getUser()->id; ?>\" />");
    _builder.newLine();
    _builder.append("<?php else: ?>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<input type=\"hidden\" name=\"jform[created_by]\" value=\"<?php echo $this->item->created_by; ?>\" />");
    _builder.newLine();
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    EList<ExtendedDetailPageField> _extendedEditedFieldsList = this.dpage.getExtendedEditedFieldsList();
    EList<ExtendedEntity> _extendedEntityList = this.dpage.getExtendedEntityList();
    ExtendedEntity _get = _extendedEntityList.get(0);
    CharSequence _generateEntytiesInputAttribute = Slug.generateEntytiesInputAttribute(_extendedEditedFieldsList, _get);
    _builder.append(_generateEntytiesInputAttribute, "");
    _builder.newLineIfNotEmpty();
    _builder.append("<div class=\"fltlft\" <?php if (!JFactory::getUser()->authorise(\'core.admin\',\'");
    String _name_3 = this.com.getName();
    String _lowerCase_3 = _name_3.toLowerCase();
    _builder.append(_lowerCase_3, "");
    _builder.append("\')): ?> style=\"display:none;\" <?php endif; ?> >");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("<?php echo JHtml::_(\'sliders.start\', \'permissions-sliders-\'.$this->item->id, array(\'useCookie\'=>1)); ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<?php echo JHtml::_(\'sliders.panel\', JText::_(\'ACL Configuration\'), \'access-rules\'); ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<fieldset class=\"panelform\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<?php echo $this->form->getLabel(\'rules\'); ?>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<?php echo $this->form->getInput(\'rules\'); ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("</fieldset>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<?php echo JHtml::_(\'sliders.end\'); ?>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<?php if (!JFactory::getUser()->authorise(\'core.admin\',\'");
    String _name_4 = this.com.getName();
    String _lowerCase_4 = _name_4.toLowerCase();
    _builder.append(_lowerCase_4, "\t\t\t\t");
    _builder.append("\')): ?>");
    _builder.newLineIfNotEmpty();
    _builder.append("                ");
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("jQuery.noConflict();");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("jQuery(\'.tab-pane select\').each(function(){");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("var option_selected = jQuery(this).find(\':selected\');");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("var input = document.createElement(\"input\");");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("input.setAttribute(\"type\", \"hidden\");");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("input.setAttribute(\"name\", jQuery(this).attr(\'name\'));");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("input.setAttribute(\"value\", option_selected.val());");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("document.getElementById(\"form-");
    String _name_5 = this.dpage.getName();
    String _lowerCase_5 = _name_5.toLowerCase();
    _builder.append(_lowerCase_5, "                       ");
    _builder.append("\").appendChild(input);");
    _builder.newLineIfNotEmpty();
    _builder.append("                    ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("             ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<div class=\"control-group\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<div class=\"controls\">");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<button type=\"submit\" class=\"validate btn btn-primary\"><?php echo JText::_(\'JSUBMIT\'); ?></button>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<a class=\"btn\" href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_6 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_6);
    String _lowerCase_6 = _nameExtensionBind_1.toLowerCase();
    _builder.append(_lowerCase_6, "                ");
    _builder.append("&task=");
    String _name_7 = this.dpage.getName();
    String _lowerCase_7 = _name_7.toLowerCase();
    _builder.append(_lowerCase_7, "                ");
    _builder.append("edit.cancel\'); ?>\" title=\"<?php echo JText::_(\'JCANCEL\'); ?>\"><?php echo JText::_(\'JCANCEL\'); ?></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<input type=\"hidden\" name=\"option\" value=\"");
    String _name_8 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_8);
    String _lowerCase_8 = _nameExtensionBind_2.toLowerCase();
    _builder.append(_lowerCase_8, "        ");
    _builder.append("\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("<input type=\"hidden\" name=\"task\" value=\"");
    String _name_9 = this.dpage.getName();
    String _lowerCase_9 = _name_9.toLowerCase();
    _builder.append(_lowerCase_9, "        ");
    _builder.append("edit.save\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("<?php echo JHtml::_(\'form.token\'); ?>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</form>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteViewLayoutShow() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?php if ($this->item ) : ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<div class=\"item_fields\">");
    _builder.newLine();
    _builder.append("<table class=\"table\">");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th><?php echo JText::_(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _upperCase = _nameExtensionBind.toUpperCase();
    _builder.append(_upperCase, "\t\t");
    _builder.append("_FORM_LBL_NONE_ID\'); ?></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td><?php echo $this->item->id; ?></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th><?php echo JText::_(\'");
    String _name_1 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_1);
    String _upperCase_1 = _nameExtensionBind_1.toUpperCase();
    _builder.append(_upperCase_1, "\t\t");
    _builder.append("_FORM_LBL_NONE_STATE\'); ?></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<i class=\"icon-<?php echo ($this->item->state == 1) ? \'publish\' : \'unpublish\'; ?>\"></i></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th><?php echo JText::_(\'");
    String _name_2 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_2);
    String _upperCase_2 = _nameExtensionBind_2.toUpperCase();
    _builder.append(_upperCase_2, "\t\t");
    _builder.append("_FORM_LBL_NONE_CREATED_BY\'); ?></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td><?php echo $this->item->created_by; ?></td>");
    _builder.newLine();
    _builder.append("</tr>");
    _builder.newLine();
    {
      EList<ExtendedAttribute> _extendedTableColumnList = this.dpage.getExtendedTableColumnList();
      for(final ExtendedAttribute a : _extendedTableColumnList) {
        EList<Entity> _entities = this.dpage.getEntities();
        Entity _get = _entities.get(0);
        CharSequence _attributShowTemplate = this.attributShowTemplate(a, _get);
        _builder.append(_attributShowTemplate, "");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("</table>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("<?php if($canEdit && $this->item->checked_out == 0): ?>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<a class=\"btn btn-primary\" href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_3 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_3);
    String _lowerCase = _nameExtensionBind_3.toLowerCase();
    _builder.append(_lowerCase, "\t");
    _builder.append("&task=");
    String _name_4 = this.dpage.getName();
    String _lowerCase_1 = _name_4.toLowerCase();
    _builder.append(_lowerCase_1, "\t");
    _builder.append("edit.edit&id=\'.$this->item->id); ?>\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<?php echo JText::_(\"");
    String _name_5 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_5);
    String _upperCase_3 = _nameExtensionBind_4.toUpperCase();
    _builder.append(_upperCase_3, "\t");
    _builder.append("_EDIT_ITEM\"); ?></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("<?php if(JFactory::getUser()->authorise(\'core.delete\',\'");
    String _name_6 = this.com.getName();
    String _nameExtensionBind_5 = Slug.nameExtensionBind("com", _name_6);
    String _lowerCase_2 = _nameExtensionBind_5.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".");
    String _name_7 = this.dpage.getName();
    String _lowerCase_3 = _name_7.toLowerCase();
    _builder.append(_lowerCase_3, "");
    _builder.append(".\'.$this->item->id)):?>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<a class=\"btn btn-danger\" href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_8 = this.com.getName();
    String _nameExtensionBind_6 = Slug.nameExtensionBind("com", _name_8);
    String _lowerCase_4 = _nameExtensionBind_6.toLowerCase();
    _builder.append(_lowerCase_4, "\t");
    _builder.append("&task=");
    String _name_9 = this.dpage.getName();
    String _lowerCase_5 = _name_9.toLowerCase();
    _builder.append(_lowerCase_5, "\t");
    _builder.append("edit.remove&id=\' . $this->item->id, false, 2); ?>\">");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<?php echo JText::_(\"");
    String _name_10 = this.com.getName();
    String _nameExtensionBind_7 = Slug.nameExtensionBind("com", _name_10);
    String _upperCase_4 = _nameExtensionBind_7.toUpperCase();
    _builder.append(_upperCase_4, "\t");
    _builder.append("_DELETE_ITEM\"); ?></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("<?php");
    _builder.newLine();
    _builder.append("else:");
    _builder.newLine();
    _builder.append("echo JText::_(\'");
    String _name_11 = this.com.getName();
    String _nameExtensionBind_8 = Slug.nameExtensionBind("com", _name_11);
    String _upperCase_5 = _nameExtensionBind_8.toUpperCase();
    _builder.append(_upperCase_5, "");
    _builder.append("_ITEM_NOT_LOADED\');");
    _builder.newLineIfNotEmpty();
    _builder.append("endif;");
    _builder.newLine();
    _builder.append("?>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence attributShowTemplate(final Attribute attr, final Entity e) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<th><?php echo JText::_(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _upperCase = _nameExtensionBind.toUpperCase();
    _builder.append(_upperCase, "\t\t");
    _builder.append("_FORM_LBL_");
    String _name_1 = e.getName();
    String _upperCase_1 = _name_1.toUpperCase();
    _builder.append(_upperCase_1, "\t\t");
    _builder.append("_");
    String _name_2 = attr.getName();
    String _upperCase_2 = _name_2.toUpperCase();
    _builder.append(_upperCase_2, "\t\t");
    _builder.append("\'); ?></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("<td><?php echo $this->item->");
    String _name_3 = attr.getName();
    String _lowerCase = _name_3.toLowerCase();
    _builder.append(_lowerCase, "\t\t");
    _builder.append("; ?></td></tr>");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
}
