package de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator;

import de.thm.icampus.joomdd.ejsl.eJSL.Attribute;
import de.thm.icampus.joomdd.ejsl.eJSL.DynamicPage;
import de.thm.icampus.joomdd.ejsl.eJSL.Entity;
import de.thm.icampus.joomdd.ejsl.eJSL.Reference;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedAttribute;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedEntity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedExtension.ExtendedComponent;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDynamicPage;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator.DynamicPageTemplate;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator.IndexPageTemplateAdminHelper;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator.IndexPageTemplateSiteHelper;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaUtil.Slug;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class IndexPageTemplate extends DynamicPageTemplate {
  private ExtendedDynamicPage ipage;
  
  private ExtendedComponent com;
  
  private String sec;
  
  private IndexPageTemplateAdminHelper helperAdmin;
  
  private IndexPageTemplateSiteHelper frontHelp;
  
  private String path;
  
  private String pagename;
  
  public IndexPageTemplate(final ExtendedDynamicPage dp, final ExtendedComponent cp, final String section, final String path, final IFileSystemAccess fsa) {
    this.ipage = dp;
    this.com = cp;
    this.sec = section;
    IndexPageTemplateAdminHelper _indexPageTemplateAdminHelper = new IndexPageTemplateAdminHelper(this.ipage, this.com, this.sec);
    this.helperAdmin = _indexPageTemplateAdminHelper;
    IndexPageTemplateSiteHelper _indexPageTemplateSiteHelper = new IndexPageTemplateSiteHelper(this.ipage, this.com, this.sec);
    this.frontHelp = _indexPageTemplateSiteHelper;
    this.path = path;
    String _name = dp.getName();
    String _lowerCase = _name.toLowerCase();
    this.pagename = _lowerCase;
    this.setFsa(fsa);
  }
  
  public void generateView() {
    boolean _equalsIgnoreCase = this.sec.equalsIgnoreCase("admin");
    if (_equalsIgnoreCase) {
      this.generateJoomlaDirectory(((this.path + "/") + this.pagename));
      CharSequence _generateViewBackend = this.generateViewBackend();
      this.generateFile(((((this.path + "/") + this.pagename) + "/") + "view.html.php"), _generateViewBackend);
      this.generateJoomlaDirectory(((((this.path + "/") + this.pagename) + "/") + "tmpl"));
      CharSequence _generateAdminViewLayoutBackend = this.generateAdminViewLayoutBackend();
      this.generateFile(((((((this.path + "/") + this.pagename) + "/") + "tmpl") + "/") + "default.php"), _generateAdminViewLayoutBackend);
    } else {
      this.generateJoomlaDirectory(((this.path + "/") + this.pagename));
      CharSequence _generateSiteView = this.generateSiteView();
      this.generateFile(((((this.path + "/") + this.pagename) + "/") + "view.html.php"), _generateSiteView);
      this.generateJoomlaDirectory(((((this.path + "/") + this.pagename) + "/") + "tmpl"));
      CharSequence _generateSiteViewLayoutShow = this.generateSiteViewLayoutShow();
      this.generateFile(((((((this.path + "/") + this.pagename) + "/") + "tmpl") + "/") + "default.php"), _generateSiteViewLayoutShow);
      CharSequence _xmlSiteTemplateContent = this.xmlSiteTemplateContent(this.pagename, this.ipage, this.com);
      this.generateFile(((((((this.path + "/") + this.pagename) + "/") + "tmpl") + "/") + "default.xml"), _xmlSiteTemplateContent);
    }
  }
  
  public CharSequence generateSiteViewLayoutShow() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, false);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    CharSequence _genViewTemplateInit = this.frontHelp.genViewTemplateInit();
    _builder.append(_genViewTemplateInit, "");
    _builder.newLineIfNotEmpty();
    CharSequence _genViewTemplateHead = this.frontHelp.genViewTemplateHead();
    _builder.append(_genViewTemplateHead, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public void generateController() {
    boolean _equalsIgnoreCase = this.sec.equalsIgnoreCase("admin");
    if (_equalsIgnoreCase) {
      CharSequence _generateAdminController = this.generateAdminController();
      this.generateFile((((this.path + "/") + this.pagename) + ".php"), _generateAdminController);
    } else {
      CharSequence _generateSiteController = this.generateSiteController();
      this.generateFile((((this.path + "/") + this.pagename) + ".php"), _generateSiteController);
    }
  }
  
  public CharSequence generateSiteController() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?php");
    _builder.newLine();
    _builder.append(" ");
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, true);
    _builder.append(_generateFileDoc, " ");
    _builder.newLineIfNotEmpty();
    _builder.append("// No direct access.");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("defined(\'_JEXEC\') or die;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("require_once JPATH_COMPONENT.\'/controller.php\';");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t ");
    _builder.append("* Sliders list controller class.");
    _builder.newLine();
    _builder.append("\t ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("class ");
    String _name = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "\t");
    _builder.append("Controller");
    String _name_1 = this.ipage.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "\t");
    _builder.append(" extends ");
    String _name_2 = this.com.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("Controller");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("* Proxy for getModel.");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("* @since\t1.6");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("public function &getModel($name = \'");
    String _name_3 = this.ipage.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_3, "\t\t");
    _builder.append("\', $prefix = \'");
    String _name_4 = this.com.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_4, "\t\t");
    _builder.append("Model\', $config = array())");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("$model = parent::getModel($name, $prefix, array(\'ignore_request\' => true));");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return $model;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public void generateModel() {
    int _compareTo = this.sec.compareTo("admin");
    boolean _equals = (_compareTo == 0);
    if (_equals) {
      CharSequence _generateAdminModel = this.generateAdminModel();
      this.generateFile((((this.path + "/") + this.pagename) + ".php"), _generateAdminModel);
      CharSequence _generateAdminModelForms = this.generateAdminModelForms();
      this.generateFile(((((this.path + "/forms/") + "filter_") + this.pagename) + ".xml"), _generateAdminModelForms);
    } else {
      CharSequence _generateSiteModelShow = this.generateSiteModelShow();
      this.generateFile((((this.path + "/") + this.pagename) + ".php"), _generateSiteModelShow);
      String _name = this.com.getName();
      CharSequence _xmlAdminFields = this.xmlAdminFields(this.ipage, this.com, _name);
      this.generateFile((((((this.path + "/forms") + "/") + "filter_") + this.pagename) + ".xml"), _xmlAdminFields);
    }
  }
  
  public CharSequence generateSiteModelShow() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, true);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("jimport(\'joomla.application.component.modellist\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Methods supporting a list of Data.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @generated");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("class ");
    String _name = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("Model");
    String _name_1 = this.ipage.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append(" extends JModelList {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _genLinkedInfo = Slug.genLinkedInfo(this.ipage, this.com);
    _builder.append(_genLinkedInfo, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminModelConstruct = this.helperAdmin.genAdminModelConstruct();
    _builder.append(_genAdminModelConstruct, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminModelGetItem = this.helperAdmin.genAdminModelGetItem();
    _builder.append(_genAdminModelGetItem, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    EList<Attribute> _filters = this.ipage.getFilters();
    CharSequence _genAdminModelGetListQuery = this.helperAdmin.genAdminModelGetListQuery(_filters);
    _builder.append(_genAdminModelGetListQuery, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genGetIdOfReferenceItem = this.helperAdmin.genGetIdOfReferenceItem();
    _builder.append(_genGetIdOfReferenceItem, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateViewBackend() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, true);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* @description ");
    EList<Entity> _entities = this.ipage.getEntities();
    Entity _get = _entities.get(0);
    String _name = _get.getName();
    _builder.append(_name, "");
    _builder.append("View for ");
    String _name_1 = this.com.getName();
    _builder.append(_name_1, "");
    _builder.newLineIfNotEmpty();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("defined(\'_JEXEC\') or die(\'Restricted access\');");
    _builder.newLine();
    _builder.append("jimport(\'joomla.application.component.view\');");
    _builder.newLine();
    _builder.append("jimport(\'joomla.filesystem.path\');");
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* ");
    String _name_2 = this.com.getName();
    _builder.append(_name_2, "");
    _builder.append("View class for component com_");
    String _name_3 = this.com.getName();
    String _slugify = Slug.slugify(_name_3);
    _builder.append(_slugify, "");
    _builder.newLineIfNotEmpty();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @category Joomla.Component. Admin");
    _builder.newLine();
    _builder.append("* @package com_");
    String _name_4 = this.com.getName();
    String _slugify_1 = Slug.slugify(_name_4);
    _builder.append(_slugify_1, "");
    _builder.append(".\"admin\"");
    _builder.newLineIfNotEmpty();
    _builder.append("* @generated");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("class ");
    String _name_5 = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_5);
    _builder.append(_firstUpper, "");
    _builder.append("View");
    String _name_6 = this.ipage.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_6);
    _builder.append(_firstUpper_1, "");
    _builder.append(" extends JViewLegacy");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append(" \t");
    _builder.append("protected $items;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected $pagination;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected $state;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _genAdminViewDisplay = this.helperAdmin.genAdminViewDisplay();
    _builder.append(_genAdminViewDisplay, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminViewAddtoolbar = this.helperAdmin.genAdminViewAddtoolbar();
    _builder.append(_genAdminViewAddtoolbar, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminViewSortFields = this.helperAdmin.genAdminViewSortFields();
    _builder.append(_genAdminViewSortFields, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminViewLayoutBackend() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, false);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    _builder.append("JHtml::addIncludePath(JPATH_COMPONENT.\'/helpers/html\');");
    _builder.newLine();
    _builder.append("JHtml::_(\'bootstrap.tooltip\');");
    _builder.newLine();
    _builder.append("JHtml::_(\'behavior.multiselect\');");
    _builder.newLine();
    _builder.append("JHtml::_(\'formbehavior.chosen\', \'select\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("// Import CSS");
    _builder.newLine();
    _builder.append("$document = JFactory::getDocument();");
    _builder.newLine();
    CharSequence _genAdminViewLayoutHeader = this.helperAdmin.genAdminViewLayoutHeader();
    _builder.append(_genAdminViewLayoutHeader, "");
    _builder.newLineIfNotEmpty();
    CharSequence _genAdminViewLayoutForm = this.helperAdmin.genAdminViewLayoutForm();
    _builder.append(_genAdminViewLayoutForm, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence generateAdminModel() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, true);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("jimport(\'joomla.application.component.modellist\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Methods supporting a list of Data.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* @generated");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("class ");
    String _name = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("Model");
    String _name_1 = this.ipage.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append(" extends JModelList {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    {
      EList<Entity> _entities = this.ipage.getEntities();
      Entity _get = _entities.get(0);
      EList<Reference> _references = _get.getReferences();
      boolean _isEmpty = _references.isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        _builder.append("\t");
        CharSequence _genLinkedInfo = Slug.genLinkedInfo(this.ipage, this.com);
        _builder.append(_genLinkedInfo, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    CharSequence _genAdminModelConstruct = this.helperAdmin.genAdminModelConstruct();
    _builder.append(_genAdminModelConstruct, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminModelGetItem = this.helperAdmin.genAdminModelGetItem();
    _builder.append(_genAdminModelGetItem, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    EList<Attribute> _filters = this.ipage.getFilters();
    CharSequence _genAdminModelGetListQuery = this.helperAdmin.genAdminModelGetListQuery(_filters);
    _builder.append(_genAdminModelGetListQuery, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminModelSaveOrder = this.helperAdmin.genAdminModelSaveOrder();
    _builder.append(_genAdminModelSaveOrder, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminModelPopulateState = this.helperAdmin.genAdminModelPopulateState();
    _builder.append(_genAdminModelPopulateState, "\t");
    _builder.newLineIfNotEmpty();
    {
      EList<Entity> _entities_1 = this.ipage.getEntities();
      Entity _get_1 = _entities_1.get(0);
      EList<Reference> _references_1 = _get_1.getReferences();
      boolean _isEmpty_1 = _references_1.isEmpty();
      boolean _not_1 = (!_isEmpty_1);
      if (_not_1) {
        CharSequence _genGetIdOfReferenceItem = this.helperAdmin.genGetIdOfReferenceItem();
        _builder.append(_genGetIdOfReferenceItem, "");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminController() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _generateFileDoc = this.generateFileDoc(this.ipage, this.com, true);
    _builder.append(_generateFileDoc, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("jimport(\'joomla.application.component.controlleradmin\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* ");
    String _name = this.ipage.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, " ");
    _builder.append(" list controller .");
    _builder.newLineIfNotEmpty();
    _builder.append(" ");
    _builder.append("* @generated");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("class ");
    String _name_1 = this.com.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append("Controller");
    String _name_2 = this.ipage.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_2, "");
    _builder.append(" extends JControllerAdmin");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    CharSequence _genAdminControllerContructer = this.helperAdmin.genAdminControllerContructer();
    _builder.append(_genAdminControllerContructer, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminControllerSaveOrdering = this.helperAdmin.genAdminControllerSaveOrdering();
    _builder.append(_genAdminControllerSaveOrdering, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _genAdminControllerGetModel = this.helperAdmin.genAdminControllerGetModel();
    _builder.append(_genAdminControllerGetModel, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteView() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    DynamicPage _instance = this.ipage.getInstance();
    CharSequence _generateFileDoc = this.generateFileDoc(_instance, this.com, true);
    _builder.append(_generateFileDoc, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("jimport(\'joomla.application.component.view\');");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* View to  Show the Data");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("class ");
    String _name = this.com.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("View");
    String _name_1 = this.ipage.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append(" extends JViewLegacy {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected $state;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected $item;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected $form;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected $params;");
    _builder.newLine();
    _builder.append("    ");
    CharSequence _generateSiteViewDisplay = this.frontHelp.generateSiteViewDisplay();
    _builder.append(_generateSiteViewDisplay, "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    CharSequence _generateSiteViewprepareDocument = this.frontHelp.generateSiteViewprepareDocument();
    _builder.append(_generateSiteViewprepareDocument, "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("} ");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateAdminModelForms() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
    _builder.newLine();
    _builder.append("<form>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<fields name=\"filter\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<field");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("name=\"search\"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("type=\"text\"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("label=\"");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _upperCase = _nameExtensionBind.toUpperCase();
    _builder.append(_upperCase, "                ");
    _builder.append("_FILTER_SEARCH_DESC\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("description=\"");
    String _name_1 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_1);
    String _upperCase_1 = _nameExtensionBind_1.toUpperCase();
    _builder.append(_upperCase_1, "            ");
    _builder.append("_FILTER_SEARCH_DESC\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("hint=\"JSEARCH_FILTER\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<field");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"state\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("type=\"status\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("label=\"");
    String _name_2 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_2);
    String _upperCase_2 = _nameExtensionBind_2.toUpperCase();
    _builder.append(_upperCase_2, "            ");
    _builder.append("_FILTER_PUBLISHED\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("description=\"");
    String _name_3 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_3);
    String _upperCase_3 = _nameExtensionBind_3.toUpperCase();
    _builder.append(_upperCase_3, "            ");
    _builder.append("_FILTER_PUBLISHED_DESC\"");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("onchange=\"this.form.submit();\"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<option value=\"\">JOPTION_SELECT_PUBLISHED</option>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</field>");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("<field");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("name=\"created_by\"");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("type=\"");
    String _name_4 = this.com.getName();
    String _lowerCase = _name_4.toLowerCase();
    _builder.append(_lowerCase, "           ");
    _builder.append("user\"");
    _builder.newLineIfNotEmpty();
    _builder.append("           ");
    _builder.append("label=\"");
    String _name_5 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_5);
    String _upperCase_4 = _nameExtensionBind_4.toUpperCase();
    _builder.append(_upperCase_4, "           ");
    _builder.append("_FILTER_CREATED_BY\"");
    _builder.newLineIfNotEmpty();
    _builder.append("           ");
    _builder.append("description=\"");
    String _name_6 = this.com.getName();
    String _nameExtensionBind_5 = Slug.nameExtensionBind("com", _name_6);
    String _upperCase_5 = _nameExtensionBind_5.toUpperCase();
    _builder.append(_upperCase_5, "           ");
    _builder.append("_FILTER_CREATED_BY\"");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("entity = \"");
    EList<ExtendedEntity> _extendedEntityList = this.ipage.getExtendedEntityList();
    ExtendedEntity _get = _extendedEntityList.get(0);
    String _name_7 = _get.getName();
    String _lowerCase_1 = _name_7.toLowerCase();
    _builder.append(_lowerCase_1, "            ");
    _builder.append("\"");
    _builder.newLineIfNotEmpty();
    _builder.append("           ");
    _builder.append("onchange=\"this.form.submit();\"");
    _builder.newLine();
    _builder.append("           ");
    _builder.append(">");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("<option value=\"\">JOPTION_SELECT_CREATED_BY</option>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</field>");
    _builder.newLine();
    {
      EList<ExtendedAttribute> _extendFiltersList = this.ipage.getExtendFiltersList();
      for(final ExtendedAttribute attr : _extendFiltersList) {
        _builder.append("       ");
        _builder.append("<field");
        _builder.newLine();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append("name=\"");
        String _name_8 = attr.getName();
        _builder.append(_name_8, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append("type=\"");
        EList<ExtendedEntity> _extendedEntityList_1 = this.ipage.getExtendedEntityList();
        ExtendedEntity _get_1 = _extendedEntityList_1.get(0);
        String _name_9 = _get_1.getName();
        String _lowerCase_2 = _name_9.toLowerCase();
        _builder.append(_lowerCase_2, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append("label=\"");
        String _name_10 = this.com.getName();
        String _nameExtensionBind_6 = Slug.nameExtensionBind("com", _name_10);
        String _upperCase_6 = _nameExtensionBind_6.toUpperCase();
        _builder.append(_upperCase_6, "            ");
        _builder.append("_FILTER_");
        String _name_11 = attr.getName();
        String _upperCase_7 = _name_11.toUpperCase();
        _builder.append(_upperCase_7, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append("description=\"");
        String _name_12 = this.com.getName();
        String _nameExtensionBind_7 = Slug.nameExtensionBind("com", _name_12);
        String _upperCase_8 = _nameExtensionBind_7.toUpperCase();
        _builder.append(_upperCase_8, "            ");
        _builder.append("_FILTER_");
        String _name_13 = attr.getName();
        String _upperCase_9 = _name_13.toUpperCase();
        _builder.append(_upperCase_9, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("      ");
        _builder.append("valueColumn=\"");
        String _name_14 = attr.getName();
        String _lowerCase_3 = _name_14.toLowerCase();
        _builder.append(_lowerCase_3, "             ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("      ");
        _builder.append("textColumn=\"");
        String _name_15 = attr.getName();
        String _lowerCase_4 = _name_15.toLowerCase();
        _builder.append(_lowerCase_4, "             ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append("onchange=\"this.form.submit();\"");
        _builder.newLine();
        _builder.append("       ");
        _builder.append("     ");
        _builder.append(">");
        _builder.newLine();
        _builder.append("       ");
        _builder.append(" ");
        _builder.append("<option value=\"\">JOPTION_SELECT_");
        String _name_16 = attr.getName();
        String _upperCase_10 = _name_16.toUpperCase();
        _builder.append(_upperCase_10, "        ");
        _builder.append("</option>");
        _builder.newLineIfNotEmpty();
        _builder.append("        ");
        _builder.append("</field>");
        _builder.newLine();
      }
    }
    _builder.append("         ");
    _builder.append("</fields>");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("</form>");
    _builder.newLine();
    return _builder;
  }
}
