package de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaPageGenerator;

import de.thm.icampus.joomdd.ejsl.eJSL.Attribute;
import de.thm.icampus.joomdd.ejsl.eJSL.Component;
import de.thm.icampus.joomdd.ejsl.eJSL.DetailsPage;
import de.thm.icampus.joomdd.ejsl.eJSL.Entity;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedEntity.ExtendedAttribute;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedExtension.ExtendedComponent;
import de.thm.icampus.joomdd.ejsl.generator.pi.ExtendedPage.ExtendedDynamicPage;
import de.thm.icampus.joomdd.ejsl.generator.ps.JoomlaUtil.Slug;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class IndexPageTemplateSiteHelper {
  private ExtendedDynamicPage indexpage;
  
  private ExtendedComponent com;
  
  private String sec;
  
  private DetailsPage details;
  
  public IndexPageTemplateSiteHelper(final ExtendedDynamicPage dp, final ExtendedComponent cp, final String section) {
    this.indexpage = dp;
    this.com = cp;
    this.sec = section;
    DetailsPage _pageForDetails = Slug.getPageForDetails(this.indexpage, this.com);
    this.details = _pageForDetails;
  }
  
  public CharSequence generateSiteViewDisplay() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Display the view");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public function display($tpl = null) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        \t ");
    _builder.append("$this->state = $this->get(\'State\');");
    _builder.newLine();
    _builder.append("       \t\t ");
    _builder.append("$this->items = $this->get(\'Items\');");
    _builder.newLine();
    _builder.append("        \t ");
    _builder.append("$this->pagination = $this->get(\'Pagination\');");
    _builder.newLine();
    _builder.append("        \t ");
    _builder.append("$this->filterForm    = $this->get(\'FilterForm\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->params = $app->getParams(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _lowerCase = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Check for errors.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (count($errors = $this->get(\'Errors\'))) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new Exception(implode(\"\\n\", $errors));");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$this->_prepareDocument();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("parent::display($tpl);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateSiteViewprepareDocument() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* Prepares the document");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("protected function _prepareDocument() {");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$app = JFactory::getApplication();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$menus = $app->getMenu();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$title = null;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("// Because the application sets a default page title,");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("// we need to get it from the menu item itself");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$menu = $menus->getActive();");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($menu) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->params->def(\'page_heading\', $this->params->get(\'page_title\', $menu->title));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->params->def(\'page_heading\', JText::_(\'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _upperCase = _nameExtensionBind.toUpperCase();
    _builder.append(_upperCase, "           ");
    _builder.append("_DEFAULT_PAGE_TITLE\'));");
    _builder.newLineIfNotEmpty();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$title = $this->params->get(\'page_title\', \'\');");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if (empty($title)) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = $app->getCfg(\'sitename\');");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} elseif ($app->getCfg(\'sitename_pagetitles\', 0) == 1) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = JText::sprintf(\'JPAGETITLE\', $app->getCfg(\'sitename\'), $title);");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("} elseif ($app->getCfg(\'sitename_pagetitles\', 0) == 2) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$title = JText::sprintf(\'JPAGETITLE\', $title, $app->getCfg(\'sitename\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("$this->document->setTitle($title);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'menu-meta_description\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setDescription($this->params->get(\'menu-meta_description\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'menu-meta_keywords\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setMetadata(\'keywords\', $this->params->get(\'menu-meta_keywords\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("if ($this->params->get(\'robots\')) {");
    _builder.newLine();
    _builder.append("           ");
    _builder.append("$this->document->setMetadata(\'robots\', $this->params->get(\'robots\'));");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence genViewTemplateInit() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JHtml::addIncludePath(JPATH_COMPONENT . \'/helpers/html\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JHtml::_(\'bootstrap.tooltip\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JHtml::_(\'behavior.multiselect\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JHtml::_(\'formbehavior.chosen\', \'select\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$user = JFactory::getUser();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$userId = $user->get(\'id\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$listOrder = $this->state->get(\'list.ordering\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$listDirn = $this->state->get(\'list.direction\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("$canCreate = $user->authorise(\'core.create\', \'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _lowerCase = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase, "\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("$canEdit = $user->authorise(\'core.edit\', \'");
    String _name_1 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_1);
    String _lowerCase_1 = _nameExtensionBind_1.toLowerCase();
    _builder.append(_lowerCase_1, "\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("$canCheckin = $user->authorise(\'core.manage\', \'");
    String _name_2 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_2);
    String _lowerCase_2 = _nameExtensionBind_2.toLowerCase();
    _builder.append(_lowerCase_2, "\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("$canChange = $user->authorise(\'core.edit.state\', \'");
    String _name_3 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_3);
    String _lowerCase_3 = _nameExtensionBind_3.toLowerCase();
    _builder.append(_lowerCase_3, "\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("$canDelete = $user->authorise(\'core.delete\', \'");
    String _name_4 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_4);
    String _lowerCase_4 = _nameExtensionBind_4.toLowerCase();
    _builder.append(_lowerCase_4, "\t");
    _builder.append("\');");
    _builder.newLineIfNotEmpty();
    _builder.append("?>");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence genViewTemplateHead() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<form action=\"<?php echo JRoute::_(\'index.php?option=");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _lowerCase = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append("&view=");
    String _name_1 = this.indexpage.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append("\'); ?>\" method=\"post\" name=\"adminForm\" id=\"adminForm\">");
    _builder.newLineIfNotEmpty();
    _builder.append("<?php echo JLayoutHelper::render(\'joomla.searchtools.default\', array(\'view\' => $this));?>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<table class=\"table table-striped\" id = \"sliderList\" >");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<thead >");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<tr >");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<?php if (isset($this->items[0]->state)): ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<th width=\"1%\" class=\"nowrap center\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php echo JHtml::_(\'grid.sort\', \'JSTATUS\', \'a.state\', $listDirn, $listOrder); ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</th>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    {
      EList<Attribute> _tablecolumns = this.indexpage.getTablecolumns();
      for(final Attribute attr : _tablecolumns) {
        _builder.append("    \t");
        _builder.append("<th class=\'left\'>");
        _builder.newLine();
        _builder.append("<?php echo JHtml::_(\'grid.sort\',  \'");
        String _name_2 = this.com.getName();
        String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_2);
        String _upperCase = _nameExtensionBind_1.toUpperCase();
        _builder.append(_upperCase, "");
        _builder.append("_FORM_LBL_");
        EObject _eContainer = attr.eContainer();
        String _name_3 = ((Entity) _eContainer).getName();
        String _upperCase_1 = _name_3.toUpperCase();
        _builder.append(_upperCase_1, "");
        _builder.append("_");
        String _name_4 = attr.getName();
        String _upperCase_2 = _name_4.toUpperCase();
        _builder.append(_upperCase_2, "");
        _builder.append("\', \'a.");
        String _name_5 = attr.getName();
        String _lowerCase_2 = _name_5.toLowerCase();
        _builder.append(_lowerCase_2, "");
        _builder.append("\', $listDirn, $listOrder); ?>");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("</th>");
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("<?php if (isset($this->items[0]->id)): ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<th width=\"1%\" class=\"nowrap center hidden-phone\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php echo JHtml::_(\'grid.sort\', \'JGRID_HEADING_ID\', \'a.id\', $listDirn, $listOrder); ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</th>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<?php if ($canEdit || $canDelete): ?>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<th class=\"center\">");
    _builder.newLine();
    _builder.append("<?php echo JText::_(\'");
    String _name_6 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_6);
    String _upperCase_3 = _nameExtensionBind_2.toUpperCase();
    _builder.append(_upperCase_3, "");
    _builder.append("_");
    String _name_7 = this.indexpage.getName();
    String _upperCase_4 = _name_7.toUpperCase();
    _builder.append(_upperCase_4, "");
    _builder.append("_ACTIONS\'); ?>");
    _builder.newLineIfNotEmpty();
    _builder.append("</th>");
    _builder.newLine();
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("<tfoot>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<tr>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<td colspan=\"<?php echo isset($this->items[0]) ? count(get_object_vars($this->items[0])) : 10; ?>\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php echo $this->pagination->getListFooter(); ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</tfoot>");
    _builder.newLine();
    CharSequence _genViewTemplateBody = this.genViewTemplateBody();
    _builder.append(_genViewTemplateBody, "");
    _builder.newLineIfNotEmpty();
    _builder.append(" ");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php if ($canCreate): ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<a href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_8 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_8);
    String _lowerCase_3 = _nameExtensionBind_3.toLowerCase();
    _builder.append(_lowerCase_3, "        ");
    _builder.append("&task=");
    String _name_9 = this.details.getName();
    String _lowerCase_4 = _name_9.toLowerCase();
    _builder.append(_lowerCase_4, "        ");
    _builder.append("edit.edit&id=0\', false, 2); ?>\"");
    _builder.newLineIfNotEmpty();
    _builder.append("           ");
    _builder.append("class=\"btn btn-success btn-small\"><i");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("class=\"icon-plus\"></i> <?php echo JText::_(\'");
    String _name_10 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_10);
    String _upperCase_5 = _nameExtensionBind_4.toUpperCase();
    _builder.append(_upperCase_5, "                ");
    _builder.append("_ADD_ITEM\'); ?></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<input type=\"hidden\" name=\"task\" value=\"\"/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<input type=\"hidden\" name=\"boxchecked\" value=\"0\"/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<input type=\"hidden\" name=\"filter_order\" value=\"<?php echo $listOrder; ?>\"/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<input type=\"hidden\" name=\"filter_order_Dir\" value=\"<?php echo $listDirn; ?>\"/>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php echo JHtml::_(\'form.token\'); ?>");
    _builder.newLine();
    _builder.append("</form>");
    _builder.newLine();
    _builder.append("<script type=\"text/javascript\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("jQuery(document).ready(function () {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("jQuery(\'.delete-button\').click(deleteItem);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("});");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("function deleteItem() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("var item_id = jQuery(this).attr(\'data-item-id\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (confirm(\"<?php echo JText::_(\'");
    String _name_11 = this.com.getName();
    String _nameExtensionBind_5 = Slug.nameExtensionBind("com", _name_11);
    String _upperCase_6 = _nameExtensionBind_5.toUpperCase();
    _builder.append(_upperCase_6, "        ");
    _builder.append("_DELETE_MESSAGE\'); ?>\")) {");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("window.location.href = \'<?php echo JRoute::_(\'index.php?option=");
    String _name_12 = this.com.getName();
    String _nameExtensionBind_6 = Slug.nameExtensionBind("com", _name_12);
    String _lowerCase_5 = _nameExtensionBind_6.toLowerCase();
    _builder.append(_lowerCase_5, "            ");
    _builder.append("&task=");
    String _name_13 = this.details.getName();
    String _lowerCase_6 = _name_13.toLowerCase();
    _builder.append(_lowerCase_6, "            ");
    _builder.append("edit.remove&id=\', false, 2) ?>\' + item_id;");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("</script>    ");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence genViewTemplateBody() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php foreach ($this->items as $i => $item) : ?>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<?php $canEdit = $user->authorise(\'core.edit\', \'");
    String _name = this.com.getName();
    String _nameExtensionBind = Slug.nameExtensionBind("com", _name);
    String _lowerCase = _nameExtensionBind.toLowerCase();
    _builder.append(_lowerCase, "        ");
    _builder.append("\'); ?>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<?php if (!$canEdit && $user->authorise(\'core.edit.own\', \'");
    String _name_1 = this.com.getName();
    String _nameExtensionBind_1 = Slug.nameExtensionBind("com", _name_1);
    String _lowerCase_1 = _nameExtensionBind_1.toLowerCase();
    _builder.append(_lowerCase_1, "\t\t\t\t");
    _builder.append("\')): ?>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("<?php $canEdit = JFactory::getUser()->id == $item->created_by; ?>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("<tr class=\"row<?php echo $i % 2; ?>\">");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php if (isset($this->items[0]->state)): ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<?php $class = ($canEdit || $canChange) ? \'active\' : \'disabled\'; ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<td class=\"center\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<a class=\"btn btn-micro <?php echo $class; ?>\"");
    _builder.newLine();
    _builder.append("                       ");
    _builder.append("href=\"<?php echo ($canEdit || $canChange) ? JRoute::_(\'index.php?option=");
    String _name_2 = this.com.getName();
    String _nameExtensionBind_2 = Slug.nameExtensionBind("com", _name_2);
    String _lowerCase_2 = _nameExtensionBind_2.toLowerCase();
    _builder.append(_lowerCase_2, "                       ");
    _builder.append("&task=");
    String _name_3 = this.details.getName();
    String _lowerCase_3 = _name_3.toLowerCase();
    _builder.append(_lowerCase_3, "                       ");
    _builder.append("edit.publish&id=\' . $item->id . \'&state=\' . (($item->state + 1) % 2), false, 2) : \'#\'; ?>\">");
    _builder.newLineIfNotEmpty();
    _builder.append("                        ");
    _builder.append("<?php if ($item->state == 1): ?>");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("<i class=\"icon-publish\"></i>");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<?php else: ?>");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("<i class=\"icon-unpublish\"></i>");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("         ");
    _builder.newLine();
    _builder.append("           ");
    EList<ExtendedAttribute> _extendedTableColumnList = this.indexpage.getExtendedTableColumnList();
    CharSequence _genSiteModelAttributeReference = this.genSiteModelAttributeReference(_extendedTableColumnList, this.indexpage, this.com);
    _builder.append(_genSiteModelAttributeReference, "           ");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php if (isset($this->items[0]->id)): ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("<td class=\"center hidden-phone\">");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("<?php echo (int)$item->id; ?>");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            \t\t\t\t");
    _builder.append("<?php if ($canEdit || $canDelete): ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<td class=\"center\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<?php if ($canEdit): ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("<a href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_4 = this.com.getName();
    String _nameExtensionBind_3 = Slug.nameExtensionBind("com", _name_4);
    String _lowerCase_4 = _nameExtensionBind_3.toLowerCase();
    _builder.append(_lowerCase_4, "\t\t\t\t\t\t\t");
    _builder.append("&task=");
    String _name_5 = this.details.getName();
    String _lowerCase_5 = _name_5.toLowerCase();
    _builder.append(_lowerCase_5, "\t\t\t\t\t\t\t");
    _builder.append("edit.edit&id=\' . $item->id, false, 2); ?>\" class=\"btn btn-mini\" type=\"button\"><i class=\"icon-edit\" ></i></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<?php if ($canDelete): ?>");
    _builder.newLine();
    _builder.append("                            ");
    _builder.append("<a href=\"<?php echo JRoute::_(\'index.php?option=");
    String _name_6 = this.com.getName();
    String _nameExtensionBind_4 = Slug.nameExtensionBind("com", _name_6);
    String _lowerCase_6 = _nameExtensionBind_4.toLowerCase();
    _builder.append(_lowerCase_6, "                            ");
    _builder.append("&task=");
    String _name_7 = this.details.getName();
    String _lowerCase_7 = _name_7.toLowerCase();
    _builder.append(_lowerCase_7, "                            ");
    _builder.append("edit.remove&id=\' . $item->id, false, 2); ?>\" class=\"btn btn-mini delete-button\" type=\"button\"><i class=\"icon-trash\" ></i></a>");
    _builder.newLineIfNotEmpty();
    _builder.append("                            ");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</td>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<?php endif; ?>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<?php endforeach; ?>");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence genSiteModelAttributeReference(final EList<ExtendedAttribute> column, final ExtendedDynamicPage indexpage, final Component com) {
    StringConcatenation _builder = new StringConcatenation();
    {
      for(final ExtendedAttribute attr : column) {
        {
          Boolean _isAttributeLinked = Slug.isAttributeLinked(attr, indexpage);
          if ((_isAttributeLinked).booleanValue()) {
            _builder.newLine();
            _builder.append("<td>");
            _builder.newLine();
            _builder.append("\t");
            _builder.append("<a href=\"<?php echo JRoute::_(");
            String _name = com.getName();
            CharSequence _linkOfAttribut = Slug.linkOfAttribut(attr, indexpage, _name, "$item->");
            _builder.append(_linkOfAttribut, "\t");
            _builder.append("); ?>\">");
            _builder.newLineIfNotEmpty();
            _builder.append("\t\t");
            _builder.append("<?php echo $this->escape($item->");
            String _name_1 = attr.getName();
            String _lowerCase = _name_1.toLowerCase();
            _builder.append(_lowerCase, "\t\t");
            _builder.append("); ?></a>");
            _builder.newLineIfNotEmpty();
          } else {
            _builder.append("<td>");
            _builder.newLine();
            _builder.append("<?php echo $item->");
            String _name_2 = attr.getName();
            String _lowerCase_1 = _name_2.toLowerCase();
            _builder.append(_lowerCase_1, "");
            _builder.append("; ?>");
            _builder.newLineIfNotEmpty();
            _builder.append("</td>");
            _builder.newLine();
          }
        }
      }
    }
    return _builder;
  }
}
