/*
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import de.thm.icampus.joomdd.ejsl.idea.lang.EJSLLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class EJSLFacetType extends AbstractFacetType<EJSLFacetConfiguration> {

	public static final FacetTypeId<Facet<EJSLFacetConfiguration>> TYPEID = new FacetTypeId<Facet<EJSLFacetConfiguration>>("de.thm.icampus.joomdd.ejsl.EJSL");

	public EJSLFacetType() {
		super(TYPEID, "de.thm.icampus.joomdd.ejsl.EJSL", "EJSL");
		EJSLLanguage.INSTANCE.injectMembers(this);
	}
}
