<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eJSLGenerator" nsURI="http://www.thm.de/icampus/ejsl/Generator"
    nsPrefix="eJSL-Generator">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExtensionGenerator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="protectedRegions" upperBound="-1"
        eType="#//ProtectedRegion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slug" eType="#//Slug"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kvPairClient" eType="#//KVPairGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="eJSLGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionClient" eType="#//ExtensionGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageGenerator" eSuperTypes="#//AbstractExtensionGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensionClient" eType="#//ExtensionGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentGenerator" eSuperTypes="#//AbstractExtensionGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageClient" eType="#//PageGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleGenerator" eSuperTypes="#//AbstractExtensionGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageClient" eType="#//PageGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPageGenerator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkClient" eType="#//LinkGeneratorClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticPage" eSuperTypes="#//AbstractPageGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicPage" eSuperTypes="#//AbstractPageGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractLinkGenerator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalLink" eSuperTypes="#//AbstractLinkGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalLink" eSuperTypes="#//AbstractLinkGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextLink" eSuperTypes="#//AbstractLinkGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="PluginGenerator" eSuperTypes="#//AbstractExtensionGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryGenerator" eSuperTypes="#//AbstractExtensionGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateGenerator" eSuperTypes="#//AbstractExtensionGenerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtectedRegion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Slug"/>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairInterface" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairLanguage" eSuperTypes="#//KVPairInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairCSS" eSuperTypes="#//KVPairInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairPosition" eSuperTypes="#//KVPairInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionGeneratorClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="#//AbstractExtensionGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkGeneratorClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//AbstractLinkGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageGeneratorClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//AbstractPageGenerator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KVPairGeneratorClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kvPair" eType="#//KVPairInterface"/>
  </eClassifiers>
</ecore:EPackage>
