/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL.impl;

import de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypeKinds;
import de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypes;
import de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage;
import de.thm.icampus.joomdd.ejsl.eJSL.KeyValuePair;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex HTML Types</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.ComplexHTMLTypesImpl#getHtmltype <em>Htmltype</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.ComplexHTMLTypesImpl#getKeyvaluepairs <em>Keyvaluepairs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComplexHTMLTypesImpl extends HTMLTypesImpl implements ComplexHTMLTypes
{
  /**
   * The default value of the '{@link #getHtmltype() <em>Htmltype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmltype()
   * @generated
   * @ordered
   */
  protected static final ComplexHTMLTypeKinds HTMLTYPE_EDEFAULT = ComplexHTMLTypeKinds.MULTISELECT;

  /**
   * The cached value of the '{@link #getHtmltype() <em>Htmltype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmltype()
   * @generated
   * @ordered
   */
  protected ComplexHTMLTypeKinds htmltype = HTMLTYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getKeyvaluepairs() <em>Keyvaluepairs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyvaluepairs()
   * @generated
   * @ordered
   */
  protected EList<KeyValuePair> keyvaluepairs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexHTMLTypesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EJSLPackage.Literals.COMPLEX_HTML_TYPES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComplexHTMLTypeKinds getHtmltype()
  {
    return htmltype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHtmltype(ComplexHTMLTypeKinds newHtmltype)
  {
    ComplexHTMLTypeKinds oldHtmltype = htmltype;
    htmltype = newHtmltype == null ? HTMLTYPE_EDEFAULT : newHtmltype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.COMPLEX_HTML_TYPES__HTMLTYPE, oldHtmltype, htmltype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<KeyValuePair> getKeyvaluepairs()
  {
    if (keyvaluepairs == null)
    {
      keyvaluepairs = new EObjectContainmentEList<KeyValuePair>(KeyValuePair.class, this, EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS);
    }
    return keyvaluepairs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS:
        return ((InternalEList<?>)getKeyvaluepairs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EJSLPackage.COMPLEX_HTML_TYPES__HTMLTYPE:
        return getHtmltype();
      case EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS:
        return getKeyvaluepairs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EJSLPackage.COMPLEX_HTML_TYPES__HTMLTYPE:
        setHtmltype((ComplexHTMLTypeKinds)newValue);
        return;
      case EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS:
        getKeyvaluepairs().clear();
        getKeyvaluepairs().addAll((Collection<? extends KeyValuePair>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.COMPLEX_HTML_TYPES__HTMLTYPE:
        setHtmltype(HTMLTYPE_EDEFAULT);
        return;
      case EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS:
        getKeyvaluepairs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.COMPLEX_HTML_TYPES__HTMLTYPE:
        return htmltype != HTMLTYPE_EDEFAULT;
      case EJSLPackage.COMPLEX_HTML_TYPES__KEYVALUEPAIRS:
        return keyvaluepairs != null && !keyvaluepairs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (htmltype: ");
    result.append(htmltype);
    result.append(')');
    return result.toString();
  }

} //ComplexHTMLTypesImpl
