/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL.impl;

import de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage;
import de.thm.icampus.joomdd.ejsl.eJSL.PageAction;
import de.thm.icampus.joomdd.ejsl.eJSL.PageActionKind;
import de.thm.icampus.joomdd.ejsl.eJSL.PageActionPositionKind;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Page Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageActionImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageActionImpl#getPageActionType <em>Page Action Type</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageActionImpl#getPageActionPosition <em>Page Action Position</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PageActionImpl extends MinimalEObjectImpl.Container implements PageAction
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPageActionType() <em>Page Action Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPageActionType()
   * @generated
   * @ordered
   */
  protected static final PageActionKind PAGE_ACTION_TYPE_EDEFAULT = PageActionKind.TEXT;

  /**
   * The cached value of the '{@link #getPageActionType() <em>Page Action Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPageActionType()
   * @generated
   * @ordered
   */
  protected PageActionKind pageActionType = PAGE_ACTION_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getPageActionPosition() <em>Page Action Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPageActionPosition()
   * @generated
   * @ordered
   */
  protected static final PageActionPositionKind PAGE_ACTION_POSITION_EDEFAULT = PageActionPositionKind.TOP;

  /**
   * The cached value of the '{@link #getPageActionPosition() <em>Page Action Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPageActionPosition()
   * @generated
   * @ordered
   */
  protected PageActionPositionKind pageActionPosition = PAGE_ACTION_POSITION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PageActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EJSLPackage.Literals.PAGE_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.PAGE_ACTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageActionKind getPageActionType()
  {
    return pageActionType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPageActionType(PageActionKind newPageActionType)
  {
    PageActionKind oldPageActionType = pageActionType;
    pageActionType = newPageActionType == null ? PAGE_ACTION_TYPE_EDEFAULT : newPageActionType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.PAGE_ACTION__PAGE_ACTION_TYPE, oldPageActionType, pageActionType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageActionPositionKind getPageActionPosition()
  {
    return pageActionPosition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPageActionPosition(PageActionPositionKind newPageActionPosition)
  {
    PageActionPositionKind oldPageActionPosition = pageActionPosition;
    pageActionPosition = newPageActionPosition == null ? PAGE_ACTION_POSITION_EDEFAULT : newPageActionPosition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.PAGE_ACTION__PAGE_ACTION_POSITION, oldPageActionPosition, pageActionPosition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE_ACTION__NAME:
        return getName();
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_TYPE:
        return getPageActionType();
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_POSITION:
        return getPageActionPosition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE_ACTION__NAME:
        setName((String)newValue);
        return;
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_TYPE:
        setPageActionType((PageActionKind)newValue);
        return;
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_POSITION:
        setPageActionPosition((PageActionPositionKind)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE_ACTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_TYPE:
        setPageActionType(PAGE_ACTION_TYPE_EDEFAULT);
        return;
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_POSITION:
        setPageActionPosition(PAGE_ACTION_POSITION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE_ACTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_TYPE:
        return pageActionType != PAGE_ACTION_TYPE_EDEFAULT;
      case EJSLPackage.PAGE_ACTION__PAGE_ACTION_POSITION:
        return pageActionPosition != PAGE_ACTION_POSITION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", pageActionType: ");
    result.append(pageActionType);
    result.append(", pageActionPosition: ");
    result.append(pageActionPosition);
    result.append(')');
    return result.toString();
  }

} //PageActionImpl
