/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex HTML Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypes#getHtmltype <em>Htmltype</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypes#getKeyvaluepairs <em>Keyvaluepairs</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getComplexHTMLTypes()
 * @model
 * @generated
 */
public interface ComplexHTMLTypes extends HTMLTypes
{
  /**
   * Returns the value of the '<em><b>Htmltype</b></em>' attribute.
   * The literals are from the enumeration {@link de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypeKinds}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Htmltype</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Htmltype</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypeKinds
   * @see #setHtmltype(ComplexHTMLTypeKinds)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getComplexHTMLTypes_Htmltype()
   * @model
   * @generated
   */
  ComplexHTMLTypeKinds getHtmltype();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypes#getHtmltype <em>Htmltype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Htmltype</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.ComplexHTMLTypeKinds
   * @see #getHtmltype()
   * @generated
   */
  void setHtmltype(ComplexHTMLTypeKinds value);

  /**
   * Returns the value of the '<em><b>Keyvaluepairs</b></em>' containment reference list.
   * The list contents are of type {@link de.thm.icampus.joomdd.ejsl.eJSL.KeyValuePair}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keyvaluepairs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyvaluepairs</em>' containment reference list.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getComplexHTMLTypes_Keyvaluepairs()
   * @model containment="true"
   * @generated
   */
  EList<KeyValuePair> getKeyvaluepairs();

} // ComplexHTMLTypes
