/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.ContextLink#getLinkparameters <em>Linkparameters</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getContextLink()
 * @model
 * @generated
 */
public interface ContextLink extends InternalLink
{
  /**
   * Returns the value of the '<em><b>Linkparameters</b></em>' containment reference list.
   * The list contents are of type {@link de.thm.icampus.joomdd.ejsl.eJSL.LinkParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Linkparameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linkparameters</em>' containment reference list.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getContextLink_Linkparameters()
   * @model containment="true"
   * @generated
   */
  EList<LinkParameter> getLinkparameters();

} // ContextLink
