/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>HTML Types</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getHTMLTypes()
 * @model
 * @generated
 */
public interface HTMLTypes extends EObject
{
} // HTMLTypes
