/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plugin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Plugin#getType <em>Type</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Plugin#getEntities <em>Entities</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.Plugin#getLocalparameters <em>Localparameters</em>}</li>
 * </ul>
 *
 * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getPlugin()
 * @model
 * @generated
 */
public interface Plugin extends Extension
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.thm.icampus.joomdd.ejsl.eJSL.PluginKinds}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.PluginKinds
   * @see #setType(PluginKinds)
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getPlugin_Type()
   * @model
   * @generated
   */
  PluginKinds getType();

  /**
   * Sets the value of the '{@link de.thm.icampus.joomdd.ejsl.eJSL.Plugin#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.PluginKinds
   * @see #getType()
   * @generated
   */
  void setType(PluginKinds value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' reference list.
   * The list contents are of type {@link de.thm.icampus.joomdd.ejsl.eJSL.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' reference list.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getPlugin_Entities()
   * @model
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Localparameters</b></em>' containment reference list.
   * The list contents are of type {@link de.thm.icampus.joomdd.ejsl.eJSL.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Localparameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Localparameters</em>' containment reference list.
   * @see de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage#getPlugin_Localparameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getLocalparameters();

} // Plugin
