/*
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.serializer;

import com.google.inject.Inject;
import de.thm.icampus.joomdd.ejsl.services.EJSLGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class EJSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EJSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Attribute___WithKeyword_7_1_0_IDKeyword_7_1_1_1__q;
	protected AbstractElementAlias match_Class___MethodsKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q;
	protected AbstractElementAlias match_Component___GlobalParameterKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_Component___LanguagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q;
	protected AbstractElementAlias match_CssBlock___KeyvaluepairsKeyword_3_0_LeftCurlyBracketKeyword_3_1_RightCurlyBracketKeyword_3_3__q;
	protected AbstractElementAlias match_Datapackage___DatapackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q;
	protected AbstractElementAlias match_Datapackage___DatatypesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q;
	protected AbstractElementAlias match_Datapackage___EntitiesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_DetailsPage___Edit_fieldsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_DetailsPage___LinksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q;
	protected AbstractElementAlias match_DetailsPage___LocalparametersKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_EJSLModel___DatapackagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_EJSLModel___EntitiesKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q;
	protected AbstractElementAlias match_EJSLModel___ExtensionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q;
	protected AbstractElementAlias match_EJSLModel___GlobalparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_EJSLModel___PagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q;
	protected AbstractElementAlias match_EJSLModel___ParametergroupsKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q;
	protected AbstractElementAlias match_Entity___AttributesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_Entity___ReferencesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q;
	protected AbstractElementAlias match_ExtensionPackage___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_IndexPage___LinksKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q;
	protected AbstractElementAlias match_IndexPage___LocalparametersKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q;
	protected AbstractElementAlias match_Language___KeyvaluepairsKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q;
	protected AbstractElementAlias match_Library___ClassesKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q;
	protected AbstractElementAlias match_Library___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_Library___PackagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q;
	protected AbstractElementAlias match_Method___MethodparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_Module___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_Package___ClassesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_Package___PackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q;
	protected AbstractElementAlias match_Plugin___LanguagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q;
	protected AbstractElementAlias match_Plugin___ParametersKeyword_13_0_LeftCurlyBracketKeyword_13_1_RightCurlyBracketKeyword_13_3__q;
	protected AbstractElementAlias match_PositionParameter___CSSKeyvaluepairsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_Position___PositionparametersKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q;
	protected AbstractElementAlias match_StaticPage___LinksKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q;
	protected AbstractElementAlias match_StaticPage___LocalparametersKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q;
	protected AbstractElementAlias match_Template___CssblocksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q;
	protected AbstractElementAlias match_Template___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q;
	protected AbstractElementAlias match_Template___ParametersKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q;
	protected AbstractElementAlias match_Template___PositionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EJSLGrammarAccess) access;
		match_Attribute___WithKeyword_7_1_0_IDKeyword_7_1_1_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeAccess().getWithKeyword_7_1_0()), new TokenAlias(false, false, grammarAccess.getAttributeAccess().getIDKeyword_7_1_1_1()));
		match_Class___MethodsKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getClassAccess().getMethodsKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getClassAccess().getLeftCurlyBracketKeyword_7_1()), new TokenAlias(false, false, grammarAccess.getClassAccess().getRightCurlyBracketKeyword_7_3()));
		match_Component___GlobalParameterKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getComponentAccess().getGlobalParameterKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getComponentAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getComponentAccess().getRightCurlyBracketKeyword_8_3()));
		match_Component___LanguagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getComponentAccess().getLanguagesKeyword_9_0()), new TokenAlias(false, false, grammarAccess.getComponentAccess().getLeftCurlyBracketKeyword_9_1()), new TokenAlias(false, false, grammarAccess.getComponentAccess().getRightCurlyBracketKeyword_9_3()));
		match_CssBlock___KeyvaluepairsKeyword_3_0_LeftCurlyBracketKeyword_3_1_RightCurlyBracketKeyword_3_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCssBlockAccess().getKeyvaluepairsKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getCssBlockAccess().getLeftCurlyBracketKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getCssBlockAccess().getRightCurlyBracketKeyword_3_3()));
		match_Datapackage___DatapackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getDatapackagesKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getLeftCurlyBracketKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getRightCurlyBracketKeyword_4_3()));
		match_Datapackage___DatatypesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getDatatypesKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getLeftCurlyBracketKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getRightCurlyBracketKeyword_6_3()));
		match_Datapackage___EntitiesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getEntitiesKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getDatapackageAccess().getRightCurlyBracketKeyword_5_3()));
		match_DetailsPage___Edit_fieldsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getEdit_fieldsKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getRightCurlyBracketKeyword_5_3()));
		match_DetailsPage___LinksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getLinksKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getRightCurlyBracketKeyword_11_3()));
		match_DetailsPage___LocalparametersKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getLocalparametersKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getDetailsPageAccess().getRightCurlyBracketKeyword_8_3()));
		match_EJSLModel___DatapackagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getDatapackagesKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_8_3()));
		match_EJSLModel___EntitiesKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getEntitiesKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_7_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_7_3()));
		match_EJSLModel___ExtensionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getExtensionsKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_10_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_10_3()));
		match_EJSLModel___GlobalparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getGlobalparametersKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_5_3()));
		match_EJSLModel___PagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getPagesKeyword_9_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_9_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_9_3()));
		match_EJSLModel___ParametergroupsKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getParametergroupsKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getLeftCurlyBracketKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getEJSLModelAccess().getRightCurlyBracketKeyword_6_3()));
		match_Entity___AttributesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEntityAccess().getAttributesKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getEntityAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getEntityAccess().getRightCurlyBracketKeyword_5_3()));
		match_Entity___ReferencesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEntityAccess().getReferencesKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getEntityAccess().getLeftCurlyBracketKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getEntityAccess().getRightCurlyBracketKeyword_6_3()));
		match_ExtensionPackage___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExtensionPackageAccess().getLanguagesKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getExtensionPackageAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getExtensionPackageAccess().getRightCurlyBracketKeyword_8_3()));
		match_IndexPage___LinksKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getLinksKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getLeftCurlyBracketKeyword_10_1()), new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getRightCurlyBracketKeyword_10_3()));
		match_IndexPage___LocalparametersKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getLocalparametersKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getLeftCurlyBracketKeyword_7_1()), new TokenAlias(false, false, grammarAccess.getIndexPageAccess().getRightCurlyBracketKeyword_7_3()));
		match_Language___KeyvaluepairsKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLanguageAccess().getKeyvaluepairsKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getLanguageAccess().getLeftCurlyBracketKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getLanguageAccess().getRightCurlyBracketKeyword_4_3()));
		match_Library___ClassesKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLibraryAccess().getClassesKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getLeftCurlyBracketKeyword_10_1()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getRightCurlyBracketKeyword_10_3()));
		match_Library___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLibraryAccess().getLanguagesKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getRightCurlyBracketKeyword_8_3()));
		match_Library___PackagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLibraryAccess().getPackagesKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getLibraryAccess().getRightCurlyBracketKeyword_11_3()));
		match_Method___MethodparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getMethodAccess().getMethodparametersKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getMethodAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getMethodAccess().getRightCurlyBracketKeyword_5_3()));
		match_Module___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getModuleAccess().getLanguagesKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getModuleAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getModuleAccess().getRightCurlyBracketKeyword_8_3()));
		match_Package___ClassesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPackageAccess().getClassesKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getPackageAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getPackageAccess().getRightCurlyBracketKeyword_5_3()));
		match_Package___PackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPackageAccess().getPackagesKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getPackageAccess().getLeftCurlyBracketKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getPackageAccess().getRightCurlyBracketKeyword_4_3()));
		match_Plugin___LanguagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPluginAccess().getLanguagesKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getPluginAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getPluginAccess().getRightCurlyBracketKeyword_11_3()));
		match_Plugin___ParametersKeyword_13_0_LeftCurlyBracketKeyword_13_1_RightCurlyBracketKeyword_13_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPluginAccess().getParametersKeyword_13_0()), new TokenAlias(false, false, grammarAccess.getPluginAccess().getLeftCurlyBracketKeyword_13_1()), new TokenAlias(false, false, grammarAccess.getPluginAccess().getRightCurlyBracketKeyword_13_3()));
		match_PositionParameter___CSSKeyvaluepairsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPositionParameterAccess().getCSSKeyvaluepairsKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getPositionParameterAccess().getLeftCurlyBracketKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getPositionParameterAccess().getRightCurlyBracketKeyword_5_3()));
		match_Position___PositionparametersKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPositionAccess().getPositionparametersKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getPositionAccess().getLeftCurlyBracketKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getPositionAccess().getRightCurlyBracketKeyword_4_3()));
		match_StaticPage___LinksKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getLinksKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getLeftCurlyBracketKeyword_7_1()), new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getRightCurlyBracketKeyword_7_3()));
		match_StaticPage___LocalparametersKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getLocalparametersKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getLeftCurlyBracketKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getStaticPageAccess().getRightCurlyBracketKeyword_6_3()));
		match_Template___CssblocksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getCssblocksKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getRightCurlyBracketKeyword_11_3()));
		match_Template___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLanguagesKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLeftCurlyBracketKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getRightCurlyBracketKeyword_8_3()));
		match_Template___ParametersKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getParametersKeyword_9_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLeftCurlyBracketKeyword_9_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getRightCurlyBracketKeyword_9_3()));
		match_Template___PositionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getPositionsKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLeftCurlyBracketKeyword_10_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getRightCurlyBracketKeyword_10_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getQualifiedNameRule())
			return getQualifiedNameToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * QualifiedName: MYID ('.' MYID)*;
	 */
	protected String getQualifiedNameToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal STRING	: 
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"' |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"
	 * 		;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Attribute___WithKeyword_7_1_0_IDKeyword_7_1_1_1__q.equals(syntax))
				emit_Attribute___WithKeyword_7_1_0_IDKeyword_7_1_1_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Class___MethodsKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q.equals(syntax))
				emit_Class___MethodsKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Component___GlobalParameterKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_Component___GlobalParameterKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Component___LanguagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q.equals(syntax))
				emit_Component___LanguagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CssBlock___KeyvaluepairsKeyword_3_0_LeftCurlyBracketKeyword_3_1_RightCurlyBracketKeyword_3_3__q.equals(syntax))
				emit_CssBlock___KeyvaluepairsKeyword_3_0_LeftCurlyBracketKeyword_3_1_RightCurlyBracketKeyword_3_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Datapackage___DatapackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q.equals(syntax))
				emit_Datapackage___DatapackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Datapackage___DatatypesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q.equals(syntax))
				emit_Datapackage___DatatypesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Datapackage___EntitiesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_Datapackage___EntitiesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DetailsPage___Edit_fieldsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_DetailsPage___Edit_fieldsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DetailsPage___LinksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q.equals(syntax))
				emit_DetailsPage___LinksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DetailsPage___LocalparametersKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_DetailsPage___LocalparametersKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___DatapackagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_EJSLModel___DatapackagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___EntitiesKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q.equals(syntax))
				emit_EJSLModel___EntitiesKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___ExtensionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q.equals(syntax))
				emit_EJSLModel___ExtensionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___GlobalparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_EJSLModel___GlobalparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___PagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q.equals(syntax))
				emit_EJSLModel___PagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EJSLModel___ParametergroupsKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q.equals(syntax))
				emit_EJSLModel___ParametergroupsKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entity___AttributesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_Entity___AttributesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entity___ReferencesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q.equals(syntax))
				emit_Entity___ReferencesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExtensionPackage___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_ExtensionPackage___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_IndexPage___LinksKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q.equals(syntax))
				emit_IndexPage___LinksKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_IndexPage___LocalparametersKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q.equals(syntax))
				emit_IndexPage___LocalparametersKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Language___KeyvaluepairsKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q.equals(syntax))
				emit_Language___KeyvaluepairsKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Library___ClassesKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q.equals(syntax))
				emit_Library___ClassesKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Library___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_Library___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Library___PackagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q.equals(syntax))
				emit_Library___PackagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Method___MethodparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_Method___MethodparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Module___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_Module___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Package___ClassesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_Package___ClassesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Package___PackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q.equals(syntax))
				emit_Package___PackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Plugin___LanguagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q.equals(syntax))
				emit_Plugin___LanguagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Plugin___ParametersKeyword_13_0_LeftCurlyBracketKeyword_13_1_RightCurlyBracketKeyword_13_3__q.equals(syntax))
				emit_Plugin___ParametersKeyword_13_0_LeftCurlyBracketKeyword_13_1_RightCurlyBracketKeyword_13_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PositionParameter___CSSKeyvaluepairsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_PositionParameter___CSSKeyvaluepairsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Position___PositionparametersKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q.equals(syntax))
				emit_Position___PositionparametersKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StaticPage___LinksKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q.equals(syntax))
				emit_StaticPage___LinksKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StaticPage___LocalparametersKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q.equals(syntax))
				emit_StaticPage___LocalparametersKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template___CssblocksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q.equals(syntax))
				emit_Template___CssblocksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q.equals(syntax))
				emit_Template___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template___ParametersKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q.equals(syntax))
				emit_Template___ParametersKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template___PositionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q.equals(syntax))
				emit_Template___PositionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('with' 'ID')?
	 *
	 * This ambiguous syntax occurs at:
	 *     isunique?='Unique attribute' (ambiguity) '}' (rule end)
	 */
	protected void emit_Attribute___WithKeyword_7_1_0_IDKeyword_7_1_1_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('methods' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|STRING] (ambiguity) '}' (rule end)
	 *     name=MYID '{' (ambiguity) '}' (rule end)
	 *     references+=[Class|QualifiedName] (ambiguity) '}' (rule end)
	 *     supertype=[Class|QualifiedName] '{' (ambiguity) '}' (rule end)
	 */
	protected void emit_Class___MethodsKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('Global parameter' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     manifest=Manifestation '}' (ambiguity) 'languages' '{' languages+=Language
	 *     manifest=Manifestation '}' (ambiguity) ('languages' '{' '}')? 'sections' '{' sections+=Section
	 */
	protected void emit_Component___GlobalParameterKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     globalParamter+=ParameterGroup '}' (ambiguity) 'sections' '{' sections+=Section
	 *     manifest=Manifestation '}' ('Global parameter' '{' '}')? (ambiguity) 'sections' '{' sections+=Section
	 */
	protected void emit_Component___LanguagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('keyvaluepairs' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     selector=STRING '(' (ambiguity) ')' (rule end)
	 */
	protected void emit_CssBlock___KeyvaluepairsKeyword_3_0_LeftCurlyBracketKeyword_3_1_RightCurlyBracketKeyword_3_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('datapackages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' (ambiguity) 'entities' '{' entities+=Entity
	 *     name=ID '{' (ambiguity) ('entities' '{' '}')? 'datatypes' '{' datatypes+=Datatype
	 *     name=ID '{' (ambiguity) ('entities' '{' '}')? ('datatypes' '{' '}')? '}' (rule end)
	 */
	protected void emit_Datapackage___DatapackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('datatypes' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datapackages+=Datapackage '}' ('entities' '{' '}')? (ambiguity) '}' (rule end)
	 *     entities+=Entity '}' (ambiguity) '}' (rule end)
	 *     name=ID '{' ('datapackages' '{' '}')? ('entities' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_Datapackage___DatatypesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('entities' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datapackages+=Datapackage '}' (ambiguity) 'datatypes' '{' datatypes+=Datatype
	 *     datapackages+=Datapackage '}' (ambiguity) ('datatypes' '{' '}')? '}' (rule end)
	 *     name=ID '{' ('datapackages' '{' '}')? (ambiguity) 'datatypes' '{' datatypes+=Datatype
	 *     name=ID '{' ('datapackages' '{' '}')? (ambiguity) ('datatypes' '{' '}')? '}' (rule end)
	 */
	protected void emit_Datapackage___EntitiesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('edit_fields' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|QualifiedName] (ambiguity) '*Globalparameters' globalparameters+=[Parameter|ID]
	 *     entities+=[Entity|QualifiedName] (ambiguity) '*ParameterGroups' parametergroups+=[ParameterGroup|ID]
	 *     entities+=[Entity|QualifiedName] (ambiguity) 'localparameters' '{' localparameters+=Parameter
	 *     entities+=[Entity|QualifiedName] (ambiguity) ('localparameters' '{' '}')? 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] (ambiguity) ('localparameters' '{' '}')? 'links' '{' links+=Link
	 *     entities+=[Entity|QualifiedName] (ambiguity) ('localparameters' '{' '}')? 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] (ambiguity) ('localparameters' '{' '}')? ('links' '{' '}')? '}' (rule end)
	 *     name=MYID '{' (ambiguity) '*Globalparameters' globalparameters+=[Parameter|ID]
	 *     name=MYID '{' (ambiguity) '*ParameterGroups' parametergroups+=[ParameterGroup|ID]
	 *     name=MYID '{' (ambiguity) 'localparameters' '{' localparameters+=Parameter
	 *     name=MYID '{' (ambiguity) ('localparameters' '{' '}')? 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     name=MYID '{' (ambiguity) ('localparameters' '{' '}')? 'links' '{' links+=Link
	 *     name=MYID '{' (ambiguity) ('localparameters' '{' '}')? 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     name=MYID '{' (ambiguity) ('localparameters' '{' '}')? ('links' '{' '}')? '}' (rule end)
	 */
	protected void emit_DetailsPage___Edit_fieldsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('links' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     editfields+=DetailPageField '}' ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     entities+=[Entity|QualifiedName] ('edit_fields' '{' '}')? ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     filters+=[Attribute|QualifiedName] (ambiguity) '}' (rule end)
	 *     globalparameters+=[Parameter|ID] ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     localparameters+=Parameter '}' (ambiguity) '}' (rule end)
	 *     name=MYID '{' ('edit_fields' '{' '}')? ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     parametergroups+=[ParameterGroup|ID] ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     tablecolumns+=[Attribute|QualifiedName] (ambiguity) '}' (rule end)
	 */
	protected void emit_DetailsPage___LinksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('localparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     editfields+=DetailPageField '}' (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     editfields+=DetailPageField '}' (ambiguity) 'links' '{' links+=Link
	 *     editfields+=DetailPageField '}' (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     editfields+=DetailPageField '}' (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     entities+=[Entity|QualifiedName] ('edit_fields' '{' '}')? (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] ('edit_fields' '{' '}')? (ambiguity) 'links' '{' links+=Link
	 *     entities+=[Entity|QualifiedName] ('edit_fields' '{' '}')? (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] ('edit_fields' '{' '}')? (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'links' '{' links+=Link
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     globalparameters+=[Parameter|ID] (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     name=MYID '{' ('edit_fields' '{' '}')? (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     name=MYID '{' ('edit_fields' '{' '}')? (ambiguity) 'links' '{' links+=Link
	 *     name=MYID '{' ('edit_fields' '{' '}')? (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     name=MYID '{' ('edit_fields' '{' '}')? (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'links' '{' links+=Link
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) ('links' '{' '}')? '}' (rule end)
	 */
	protected void emit_DetailsPage___LocalparametersKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('datapackages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) 'pages' '{' pages+=Page
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     entities+=Entity '}' (ambiguity) 'pages' '{' pages+=Page
	 *     entities+=Entity '}' (ambiguity) ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     entities+=Entity '}' (ambiguity) ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) 'pages' '{' pages+=Page
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) 'pages' '{' pages+=Page
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? (ambiguity) 'pages' '{' pages+=Page
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? (ambiguity) ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 */
	protected void emit_EJSLModel___DatapackagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('entities' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) 'datapackages' '{' datapackages+=Datapackage
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? (ambiguity) 'datapackages' '{' datapackages+=Datapackage
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) 'datapackages' '{' datapackages+=Datapackage
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     parametergroups+=ParameterGroup '}' (ambiguity) 'datapackages' '{' datapackages+=Datapackage
	 *     parametergroups+=ParameterGroup '}' (ambiguity) ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     parametergroups+=ParameterGroup '}' (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     parametergroups+=ParameterGroup '}' (ambiguity) ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 */
	protected void emit_EJSLModel___EntitiesKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('extensions' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datapackages+=Datapackage '}' ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 *     entities+=Entity '}' ('datapackages' '{' '}')? ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 *     pages+=Page '}' (ambiguity) '}' (rule end)
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_EJSLModel___ExtensionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('globalparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datatypes+=Datatype '}' (ambiguity) 'parametergroups' '{' parametergroups+=ParameterGroup
	 *     datatypes+=Datatype '}' (ambiguity) ('parametergroups' '{' '}')? 'entities' '{' entities+=Entity
	 *     datatypes+=Datatype '}' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? 'datapackages' '{' datapackages+=Datapackage
	 *     datatypes+=Datatype '}' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     datatypes+=Datatype '}' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     datatypes+=Datatype '}' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     name=STRING '{' (ambiguity) 'parametergroups' '{' parametergroups+=ParameterGroup
	 *     name=STRING '{' (ambiguity) ('parametergroups' '{' '}')? 'entities' '{' entities+=Entity
	 *     name=STRING '{' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? 'datapackages' '{' datapackages+=Datapackage
	 *     name=STRING '{' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     name=STRING '{' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     name=STRING '{' (ambiguity) ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 */
	protected void emit_EJSLModel___GlobalparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('pages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datapackages+=Datapackage '}' (ambiguity) 'extensions' '{' extensions+=Extension
	 *     datapackages+=Datapackage '}' (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) 'extensions' '{' extensions+=Extension
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 *     entities+=Entity '}' ('datapackages' '{' '}')? (ambiguity) 'extensions' '{' extensions+=Extension
	 *     entities+=Entity '}' ('datapackages' '{' '}')? (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) 'extensions' '{' extensions+=Extension
	 *     globalparameters+=Parameter '}' ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) 'extensions' '{' extensions+=Extension
	 *     name=STRING '{' ('globalparameters' '{' '}')? ('parametergroups' '{' '}')? ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) 'extensions' '{' extensions+=Extension
	 *     parametergroups+=ParameterGroup '}' ('entities' '{' '}')? ('datapackages' '{' '}')? (ambiguity) ('extensions' '{' '}')? '}' (rule end)
	 */
	protected void emit_EJSLModel___PagesKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('parametergroups' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? (ambiguity) 'entities' '{' entities+=Entity
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? 'datapackages' '{' datapackages+=Datapackage
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     datatypes+=Datatype '}' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     globalparameters+=Parameter '}' (ambiguity) 'entities' '{' entities+=Entity
	 *     globalparameters+=Parameter '}' (ambiguity) ('entities' '{' '}')? 'datapackages' '{' datapackages+=Datapackage
	 *     globalparameters+=Parameter '}' (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     globalparameters+=Parameter '}' (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     globalparameters+=Parameter '}' (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 *     name=STRING '{' ('globalparameters' '{' '}')? (ambiguity) 'entities' '{' entities+=Entity
	 *     name=STRING '{' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? 'datapackages' '{' datapackages+=Datapackage
	 *     name=STRING '{' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? 'pages' '{' pages+=Page
	 *     name=STRING '{' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? 'extensions' '{' extensions+=Extension
	 *     name=STRING '{' ('globalparameters' '{' '}')? (ambiguity) ('entities' '{' '}')? ('datapackages' '{' '}')? ('pages' '{' '}')? ('extensions' '{' '}')? '}' (rule end)
	 */
	protected void emit_EJSLModel___ParametergroupsKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('attributes' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=MYID '{' (ambiguity) 'references' '{' references+=Reference
	 *     name=MYID '{' (ambiguity) ('references' '{' '}')? '}' (rule end)
	 *     supertype=[Entity|QualifiedName] '{' (ambiguity) 'references' '{' references+=Reference
	 *     supertype=[Entity|QualifiedName] '{' (ambiguity) ('references' '{' '}')? '}' (rule end)
	 */
	protected void emit_Entity___AttributesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('references' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     attributes+=Attribute '}' (ambiguity) '}' (rule end)
	 *     name=MYID '{' ('attributes' '{' '}')? (ambiguity) '}' (rule end)
	 *     supertype=[Entity|QualifiedName] '{' ('attributes' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_Entity___ReferencesKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     manifest=Manifestation '}' (ambiguity) 'extensions' '{' extensions+=Extension
	 */
	protected void emit_ExtensionPackage___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('links' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|QualifiedName] ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     filters+=[Attribute|QualifiedName] (ambiguity) '}' (rule end)
	 *     globalparameters+=[Parameter|ID] ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     localparameters+=Parameter '}' (ambiguity) '}' (rule end)
	 *     name=MYID '{' ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     parametergroups+=[ParameterGroup|ID] ('localparameters' '{' '}')? (ambiguity) '}' (rule end)
	 *     tablecolumns+=[Attribute|QualifiedName] (ambiguity) '}' (rule end)
	 */
	protected void emit_IndexPage___LinksKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('localparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|QualifiedName] (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] (ambiguity) 'links' '{' links+=Link
	 *     entities+=[Entity|QualifiedName] (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     entities+=[Entity|QualifiedName] (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'links' '{' links+=Link
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     globalparameters+=[Parameter|ID] (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     name=MYID '{' (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     name=MYID '{' (ambiguity) 'links' '{' links+=Link
	 *     name=MYID '{' (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     name=MYID '{' (ambiguity) ('links' '{' '}')? '}' (rule end)
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'filters' '=' filters+=[Attribute|QualifiedName]
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'links' '{' links+=Link
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'table columns' '=' tablecolumns+=[Attribute|QualifiedName]
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) ('links' '{' '}')? '}' (rule end)
	 */
	protected void emit_IndexPage___LocalparametersKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('keyvaluepairs' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=LANGUAGE_CODE '{' (ambiguity) '}' (rule end)
	 */
	protected void emit_Language___KeyvaluepairsKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('classes' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|STRING] (ambiguity) 'packages' '{' packages+=Package
	 *     entities+=[Entity|STRING] (ambiguity) ('packages' '{' '}')? '}' (rule end)
	 *     languages+=Language '}' (ambiguity) 'packages' '{' packages+=Package
	 *     languages+=Language '}' (ambiguity) ('packages' '{' '}')? '}' (rule end)
	 *     manifest=Manifestation '}' ('languages' '{' '}')? (ambiguity) 'packages' '{' packages+=Package
	 *     manifest=Manifestation '}' ('languages' '{' '}')? (ambiguity) ('packages' '{' '}')? '}' (rule end)
	 */
	protected void emit_Library___ClassesKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     manifest=Manifestation '}' (ambiguity) '*Entities' entities+=[Entity|STRING]
	 *     manifest=Manifestation '}' (ambiguity) 'classes' '{' classes+=Class
	 *     manifest=Manifestation '}' (ambiguity) ('classes' '{' '}')? 'packages' '{' packages+=Package
	 *     manifest=Manifestation '}' (ambiguity) ('classes' '{' '}')? ('packages' '{' '}')? '}' (rule end)
	 */
	protected void emit_Library___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('packages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     classes+=Class '}' (ambiguity) '}' (rule end)
	 *     entities+=[Entity|STRING] ('classes' '{' '}')? (ambiguity) '}' (rule end)
	 *     languages+=Language '}' ('classes' '{' '}')? (ambiguity) '}' (rule end)
	 *     manifest=Manifestation '}' ('languages' '{' '}')? ('classes' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_Library___PackagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('methodparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=MYID '{' (ambiguity) '}' (rule end)
	 *     type=Type (ambiguity) '}' (rule end)
	 */
	protected void emit_Method___MethodparametersKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     manifest=Manifestation '}' (ambiguity) '}' (rule end)
	 *     manifest=Manifestation '}' (ambiguity) pageRef=PageReference
	 */
	protected void emit_Module___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('classes' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=MYID '{' ('packages' '{' '}')? (ambiguity) '}' (rule end)
	 *     packages+=Package '}' (ambiguity) '}' (rule end)
	 */
	protected void emit_Package___ClassesKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('packages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=MYID '{' (ambiguity) 'classes' '{' classes+=Class
	 *     name=MYID '{' (ambiguity) ('classes' '{' '}')? '}' (rule end)
	 */
	protected void emit_Package___PackagesKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=PluginKinds (ambiguity) '*Entities' entities+=[Entity|STRING]
	 *     type=PluginKinds (ambiguity) 'parameters' '{' localparameters+=Parameter
	 *     type=PluginKinds (ambiguity) ('parameters' '{' '}')? '}' (rule end)
	 */
	protected void emit_Plugin___LanguagesKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('parameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     entities+=[Entity|STRING] (ambiguity) '}' (rule end)
	 *     languages+=Language '}' (ambiguity) '}' (rule end)
	 *     type=PluginKinds ('languages' '{' '}')? (ambiguity) '}' (rule end)
	 */
	protected void emit_Plugin___ParametersKeyword_13_0_LeftCurlyBracketKeyword_13_1_RightCurlyBracketKeyword_13_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('CSS keyvaluepairs' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     divid=ID (ambiguity) '}' (rule end)
	 *     name=ID '{' (ambiguity) '}' (rule end)
	 *     type=POSITION_TYPES_NAMES (ambiguity) '}' (rule end)
	 */
	protected void emit_PositionParameter___CSSKeyvaluepairsKeyword_5_0_LeftCurlyBracketKeyword_5_1_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('positionparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' (ambiguity) '}' (rule end)
	 *     name=POSITION_TYPES '{' (ambiguity) '}' (rule end)
	 */
	protected void emit_Position___PositionparametersKeyword_4_0_LeftCurlyBracketKeyword_4_1_RightCurlyBracketKeyword_4_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('links' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     globalparameters+=[Parameter|ID] ('localparameters' '{' '}')? (ambiguity) 'HTMLBody' '{' HTMLBody=STRING
	 *     localparameters+=Parameter '}' (ambiguity) 'HTMLBody' '{' HTMLBody=STRING
	 *     name=MYID '{' ('localparameters' '{' '}')? (ambiguity) 'HTMLBody' '{' HTMLBody=STRING
	 *     parametergroups+=[ParameterGroup|ID] ('localparameters' '{' '}')? (ambiguity) 'HTMLBody' '{' HTMLBody=STRING
	 */
	protected void emit_StaticPage___LinksKeyword_7_0_LeftCurlyBracketKeyword_7_1_RightCurlyBracketKeyword_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('localparameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     globalparameters+=[Parameter|ID] (ambiguity) 'links' '{' links+=Link
	 *     globalparameters+=[Parameter|ID] (ambiguity) ('links' '{' '}')? 'HTMLBody' '{' HTMLBody=STRING
	 *     name=MYID '{' (ambiguity) 'links' '{' links+=Link
	 *     name=MYID '{' (ambiguity) ('links' '{' '}')? 'HTMLBody' '{' HTMLBody=STRING
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) 'links' '{' links+=Link
	 *     parametergroups+=[ParameterGroup|ID] (ambiguity) ('links' '{' '}')? 'HTMLBody' '{' HTMLBody=STRING
	 */
	protected void emit_StaticPage___LocalparametersKeyword_6_0_LeftCurlyBracketKeyword_6_1_RightCurlyBracketKeyword_6_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('cssblocks' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     languages+=Language '}' ('parameters' '{' '}')? ('positions' '{' '}')? (ambiguity) '}' (rule end)
	 *     localparameters+=Parameter '}' ('positions' '{' '}')? (ambiguity) '}' (rule end)
	 *     manifest=Manifestation '}' ('languages' '{' '}')? ('parameters' '{' '}')? ('positions' '{' '}')? (ambiguity) '}' (rule end)
	 *     positions+=Position '}' (ambiguity) '}' (rule end)
	 */
	protected void emit_Template___CssblocksKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('languages' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     manifest=Manifestation '}' (ambiguity) 'parameters' '{' localparameters+=Parameter
	 *     manifest=Manifestation '}' (ambiguity) ('parameters' '{' '}')? 'positions' '{' positions+=Position
	 *     manifest=Manifestation '}' (ambiguity) ('parameters' '{' '}')? ('positions' '{' '}')? 'cssblocks' '{' cssblocks+=CssBlock
	 *     manifest=Manifestation '}' (ambiguity) ('parameters' '{' '}')? ('positions' '{' '}')? ('cssblocks' '{' '}')? '}' (rule end)
	 */
	protected void emit_Template___LanguagesKeyword_8_0_LeftCurlyBracketKeyword_8_1_RightCurlyBracketKeyword_8_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('parameters' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     languages+=Language '}' (ambiguity) 'positions' '{' positions+=Position
	 *     languages+=Language '}' (ambiguity) ('positions' '{' '}')? 'cssblocks' '{' cssblocks+=CssBlock
	 *     languages+=Language '}' (ambiguity) ('positions' '{' '}')? ('cssblocks' '{' '}')? '}' (rule end)
	 *     manifest=Manifestation '}' ('languages' '{' '}')? (ambiguity) 'positions' '{' positions+=Position
	 *     manifest=Manifestation '}' ('languages' '{' '}')? (ambiguity) ('positions' '{' '}')? 'cssblocks' '{' cssblocks+=CssBlock
	 *     manifest=Manifestation '}' ('languages' '{' '}')? (ambiguity) ('positions' '{' '}')? ('cssblocks' '{' '}')? '}' (rule end)
	 */
	protected void emit_Template___ParametersKeyword_9_0_LeftCurlyBracketKeyword_9_1_RightCurlyBracketKeyword_9_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('positions' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     languages+=Language '}' ('parameters' '{' '}')? (ambiguity) 'cssblocks' '{' cssblocks+=CssBlock
	 *     languages+=Language '}' ('parameters' '{' '}')? (ambiguity) ('cssblocks' '{' '}')? '}' (rule end)
	 *     localparameters+=Parameter '}' (ambiguity) 'cssblocks' '{' cssblocks+=CssBlock
	 *     localparameters+=Parameter '}' (ambiguity) ('cssblocks' '{' '}')? '}' (rule end)
	 *     manifest=Manifestation '}' ('languages' '{' '}')? ('parameters' '{' '}')? (ambiguity) 'cssblocks' '{' cssblocks+=CssBlock
	 *     manifest=Manifestation '}' ('languages' '{' '}')? ('parameters' '{' '}')? (ambiguity) ('cssblocks' '{' '}')? '}' (rule end)
	 */
	protected void emit_Template___PositionsKeyword_10_0_LeftCurlyBracketKeyword_10_1_RightCurlyBracketKeyword_10_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
