/*
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import de.thm.icampus.joomdd.ejsl.idea.lang.EJSLLanguage;
import org.jetbrains.annotations.NotNull;

public class EJSLSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return EJSLLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
