/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL.impl;

import de.thm.icampus.joomdd.ejsl.eJSL.Author;
import de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.AuthorImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.AuthorImpl#getAuthoremail <em>Authoremail</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.AuthorImpl#getAuthorurl <em>Authorurl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AuthorImpl extends MinimalEObjectImpl.Container implements Author
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAuthoremail() <em>Authoremail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthoremail()
   * @generated
   * @ordered
   */
  protected static final String AUTHOREMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAuthoremail() <em>Authoremail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthoremail()
   * @generated
   * @ordered
   */
  protected String authoremail = AUTHOREMAIL_EDEFAULT;

  /**
   * The default value of the '{@link #getAuthorurl() <em>Authorurl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthorurl()
   * @generated
   * @ordered
   */
  protected static final String AUTHORURL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAuthorurl() <em>Authorurl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthorurl()
   * @generated
   * @ordered
   */
  protected String authorurl = AUTHORURL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AuthorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EJSLPackage.Literals.AUTHOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.AUTHOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAuthoremail()
  {
    return authoremail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAuthoremail(String newAuthoremail)
  {
    String oldAuthoremail = authoremail;
    authoremail = newAuthoremail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.AUTHOR__AUTHOREMAIL, oldAuthoremail, authoremail));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAuthorurl()
  {
    return authorurl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAuthorurl(String newAuthorurl)
  {
    String oldAuthorurl = authorurl;
    authorurl = newAuthorurl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.AUTHOR__AUTHORURL, oldAuthorurl, authorurl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EJSLPackage.AUTHOR__NAME:
        return getName();
      case EJSLPackage.AUTHOR__AUTHOREMAIL:
        return getAuthoremail();
      case EJSLPackage.AUTHOR__AUTHORURL:
        return getAuthorurl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EJSLPackage.AUTHOR__NAME:
        setName((String)newValue);
        return;
      case EJSLPackage.AUTHOR__AUTHOREMAIL:
        setAuthoremail((String)newValue);
        return;
      case EJSLPackage.AUTHOR__AUTHORURL:
        setAuthorurl((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.AUTHOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EJSLPackage.AUTHOR__AUTHOREMAIL:
        setAuthoremail(AUTHOREMAIL_EDEFAULT);
        return;
      case EJSLPackage.AUTHOR__AUTHORURL:
        setAuthorurl(AUTHORURL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.AUTHOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EJSLPackage.AUTHOR__AUTHOREMAIL:
        return AUTHOREMAIL_EDEFAULT == null ? authoremail != null : !AUTHOREMAIL_EDEFAULT.equals(authoremail);
      case EJSLPackage.AUTHOR__AUTHORURL:
        return AUTHORURL_EDEFAULT == null ? authorurl != null : !AUTHORURL_EDEFAULT.equals(authorurl);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", authoremail: ");
    result.append(authoremail);
    result.append(", authorurl: ");
    result.append(authorurl);
    result.append(')');
    return result.toString();
  }

} //AuthorImpl
