/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL.impl;

import de.thm.icampus.joomdd.ejsl.eJSL.Attribute;
import de.thm.icampus.joomdd.ejsl.eJSL.DetailPageField;
import de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage;
import de.thm.icampus.joomdd.ejsl.eJSL.HTMLTypes;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Detail Page Field</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.DetailPageFieldImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.DetailPageFieldImpl#getHtmltype <em>Htmltype</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DetailPageFieldImpl extends MinimalEObjectImpl.Container implements DetailPageField
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getHtmltype() <em>Htmltype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmltype()
   * @generated
   * @ordered
   */
  protected HTMLTypes htmltype;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DetailPageFieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EJSLPackage.Literals.DETAIL_PAGE_FIELD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HTMLTypes getHtmltype()
  {
    return htmltype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHtmltype(HTMLTypes newHtmltype, NotificationChain msgs)
  {
    HTMLTypes oldHtmltype = htmltype;
    htmltype = newHtmltype;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE, oldHtmltype, newHtmltype);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHtmltype(HTMLTypes newHtmltype)
  {
    if (newHtmltype != htmltype)
    {
      NotificationChain msgs = null;
      if (htmltype != null)
        msgs = ((InternalEObject)htmltype).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE, null, msgs);
      if (newHtmltype != null)
        msgs = ((InternalEObject)newHtmltype).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE, null, msgs);
      msgs = basicSetHtmltype(newHtmltype, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE, newHtmltype, newHtmltype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE:
        return basicSetHtmltype(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE:
        return getHtmltype();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE:
        setHtmltype((HTMLTypes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE:
        setHtmltype((HTMLTypes)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.DETAIL_PAGE_FIELD__ATTRIBUTE:
        return attribute != null;
      case EJSLPackage.DETAIL_PAGE_FIELD__HTMLTYPE:
        return htmltype != null;
    }
    return super.eIsSet(featureID);
  }

} //DetailPageFieldImpl
