/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.eJSL.impl;

import de.thm.icampus.joomdd.ejsl.eJSL.EJSLPackage;
import de.thm.icampus.joomdd.ejsl.eJSL.Link;
import de.thm.icampus.joomdd.ejsl.eJSL.Page;
import de.thm.icampus.joomdd.ejsl.eJSL.Parameter;
import de.thm.icampus.joomdd.ejsl.eJSL.ParameterGroup;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Page</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageImpl#getParametergroups <em>Parametergroups</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageImpl#getGlobalparameters <em>Globalparameters</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageImpl#getLocalparameters <em>Localparameters</em>}</li>
 *   <li>{@link de.thm.icampus.joomdd.ejsl.eJSL.impl.PageImpl#getLinks <em>Links</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PageImpl extends MinimalEObjectImpl.Container implements Page
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParametergroups() <em>Parametergroups</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametergroups()
   * @generated
   * @ordered
   */
  protected EList<ParameterGroup> parametergroups;

  /**
   * The cached value of the '{@link #getGlobalparameters() <em>Globalparameters</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGlobalparameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> globalparameters;

  /**
   * The cached value of the '{@link #getLocalparameters() <em>Localparameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocalparameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> localparameters;

  /**
   * The cached value of the '{@link #getLinks() <em>Links</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinks()
   * @generated
   * @ordered
   */
  protected EList<Link> links;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EJSLPackage.Literals.PAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EJSLPackage.PAGE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ParameterGroup> getParametergroups()
  {
    if (parametergroups == null)
    {
      parametergroups = new EObjectResolvingEList<ParameterGroup>(ParameterGroup.class, this, EJSLPackage.PAGE__PARAMETERGROUPS);
    }
    return parametergroups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Parameter> getGlobalparameters()
  {
    if (globalparameters == null)
    {
      globalparameters = new EObjectResolvingEList<Parameter>(Parameter.class, this, EJSLPackage.PAGE__GLOBALPARAMETERS);
    }
    return globalparameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Parameter> getLocalparameters()
  {
    if (localparameters == null)
    {
      localparameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, EJSLPackage.PAGE__LOCALPARAMETERS);
    }
    return localparameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Link> getLinks()
  {
    if (links == null)
    {
      links = new EObjectContainmentEList<Link>(Link.class, this, EJSLPackage.PAGE__LINKS);
    }
    return links;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE__LOCALPARAMETERS:
        return ((InternalEList<?>)getLocalparameters()).basicRemove(otherEnd, msgs);
      case EJSLPackage.PAGE__LINKS:
        return ((InternalEList<?>)getLinks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE__NAME:
        return getName();
      case EJSLPackage.PAGE__PARAMETERGROUPS:
        return getParametergroups();
      case EJSLPackage.PAGE__GLOBALPARAMETERS:
        return getGlobalparameters();
      case EJSLPackage.PAGE__LOCALPARAMETERS:
        return getLocalparameters();
      case EJSLPackage.PAGE__LINKS:
        return getLinks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE__NAME:
        setName((String)newValue);
        return;
      case EJSLPackage.PAGE__PARAMETERGROUPS:
        getParametergroups().clear();
        getParametergroups().addAll((Collection<? extends ParameterGroup>)newValue);
        return;
      case EJSLPackage.PAGE__GLOBALPARAMETERS:
        getGlobalparameters().clear();
        getGlobalparameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case EJSLPackage.PAGE__LOCALPARAMETERS:
        getLocalparameters().clear();
        getLocalparameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case EJSLPackage.PAGE__LINKS:
        getLinks().clear();
        getLinks().addAll((Collection<? extends Link>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EJSLPackage.PAGE__PARAMETERGROUPS:
        getParametergroups().clear();
        return;
      case EJSLPackage.PAGE__GLOBALPARAMETERS:
        getGlobalparameters().clear();
        return;
      case EJSLPackage.PAGE__LOCALPARAMETERS:
        getLocalparameters().clear();
        return;
      case EJSLPackage.PAGE__LINKS:
        getLinks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EJSLPackage.PAGE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EJSLPackage.PAGE__PARAMETERGROUPS:
        return parametergroups != null && !parametergroups.isEmpty();
      case EJSLPackage.PAGE__GLOBALPARAMETERS:
        return globalparameters != null && !globalparameters.isEmpty();
      case EJSLPackage.PAGE__LOCALPARAMETERS:
        return localparameters != null && !localparameters.isEmpty();
      case EJSLPackage.PAGE__LINKS:
        return links != null && !links.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PageImpl
