/**
 * generated by iCampus (JooMDD team) 2.9.1
 */
package de.thm.icampus.joomdd.ejsl.idea;

@SuppressWarnings("all")
public class EJSLIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
