/*
* generated by Xtext
*/
package de.thm.icampus.cjsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CjslStandaloneSetup extends CjslStandaloneSetupGenerated{

	public static void doSetup() {
		new CjslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

